### ISSUE TITLE
Waybill: Create a BIS description on how IDs should be used 

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#102]
Today waybill includes for example ConsigneeAssignedID, ConsignorAssignedID, Carrier'sID and FreghtForwader'sID. There has been raised a comment about the need for describing how IDs should be used. 

[Kopi av Waybill comments.xlsx](https://github.com/OpenPEPPOL/logistics-bis/files/11625663/Kopi.av.Waybill.comments.xlsx)

**Comment by areberg** [comment]
Done

**Comment by areberg** [comment]
Done

**Comment by areberg** [comment]
Done
