### ISSUE TITLE
Remove TraceID in GoodsItem 

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#103]
We decided to remove TraceID in GoodsItem in waybill. 
Need to align Transport Execution Plan and Transport Execution Plan Request. 

please complete following actions: 

- [x] remove TraceID from Goodsitem in TrasportExecutionPlanRequest
- [x] remove TraceID from Goodsitem in TrasportExecutionPlan 

https://test-docs.peppol.eu/logistics/transport-execution/syntax/TransportExecutionPlanRequest/cac-Consignment/cac-TransportHandlingUnit/cac-GoodsItem/ 

https://test-docs.peppol.eu/logistics/transport-execution/syntax/TransportExecutionPlan/cac-Consignment/cac-TransportHandlingUnit/cac-GoodsItem/

**Comment by PeterLBorresen** [comment]
Done
