### ISSUE TITLE
Cardinality in Waybill/Signature/Signatureparty/PostalAdress 

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#104]
We decided in work group to change cardinality on following actions: 

- [x] Change StreetName to optional
- [x] change CityName to optional
- [x] change PostalZone to optional
- [x] change PostalZone to optional
- [ ] change Country to optional
- [x] Change IdendificationCode under Country to mandatory 

@PeterLBorresen Peter please complete these actions. 

https://test-docs.peppol.eu/logistics/waybill/syntax/Waybill/cac-Signature/cac-SignatureParty/cac-PostalAddress/

**Comment by PeterLBorresen** [comment]
Done, but Country in an address should not be optional.
