### ISSUE TITLE
Remove PartyLegalEntity under SignatureParty

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#105]
@PeterLBorresen , please complete following action: 

- [x] remove PartyLegalEntity under SignatureParty

https://test-docs.peppol.eu/logistics/waybill/syntax/Waybill/cac-Signature/cac-SignatureParty/

[Kopi av Waybill comments.xlsx](https://github.com/OpenPEPPOL/logistics-bis/files/11626144/Kopi.av.Waybill.comments.xlsx)

**Comment by PeterLBorresen** [comment]
Done
