### ISSUE TITLE
Change Contact under SignatureParty to Person

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#106]
As we decided; change Contact under SignatureParty to Person, and add ShemeID. keep it optional. 

- [x] change contact under SignatureParty to person 
- [x] add ShemeID 

https://test-docs.peppol.eu/logistics/waybill/syntax/Waybill/cac-Signature/cac-SignatureParty/

**Comment by PeterLBorresen** [comment]
Done
