### ISSUE TITLE
Cardinality Transportation Status Request 

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#107]
Please complete following actions: 

- [x] Change issueTime to mandatory  
https://test-docs.peppol.eu/logistics/transportation-status/syntax/TransportationStatusRequest/ 

- [x] Change ShippingOrderID to mandatory, and add SchemeID
https://test-docs.peppol.eu/logistics/transportation-status/syntax/TransportationStatusRequest/ 

- [x] Change IdentificationCode to mandatory 
https://test-docs.peppol.eu/logistics/transportation-status/syntax/TransportationStatusRequest/cac-SenderParty/cac-PartyLegalEntity/cac-RegistrationAddress/cac-Country/cbc-IdentificationCode/ 

- [x] change PartyIdentification to optional  
https://test-docs.peppol.eu/logistics/transportation-status/syntax/TransportationStatusRequest/cac-ReceiverParty/

- [x] Change IdentificationCode to mandatory 
https://test-docs.peppol.eu/logistics/transportation-status/syntax/TransportationStatusRequest/cac-ReceiverParty/cac-PartyLegalEntity/cac-RegistrationAddress/cac-Country/

**Comment by agrindst** [comment]
[Kopi av StatusRequest_Status_Comments - med kommentarer fra wg.xlsx](https://github.com/OpenPEPPOL/logistics-bis/files/11753639/Kopi.av.StatusRequest_Status_Comments.-.med.kommentarer.fra.wg.xlsx)


Jörgens comment about ShippingOrderID: 
"When sending a StatusRequest I see this element as the key identification of which transport the query is about. Suggest to make it mandatory and to add a @listID to describe what type of document the ShippingOrder is. Then the reference to the TransportExecutionPlan can be removed, and it will also be possible to query om waybills, etc." 

This was then discussed in the WG-meeting where the solution then was to change it to mandatory.

**Comment by PeterLBorresen** [comment]
I have added the schemeID, but the reference to the TransportExecutionPlan should we deffently keep. We need to come up with a coherent solution. This has alsp been discusse at a project meeting before, where we agreed to keep the reference.
