### ISSUE TITLE
Transportation Status Type Code

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#108]
There is an ongoing discussion about Transportation Status types. There was a comment by Bring that it could be valuable to look into the possibility of subscribing for different information of transportation status. 

Bring could also inform that either they sent information of the latest event, or they sent information about all events. 

ongoing actions: 

- Peter is looking into different possibilities
- Atle will look at possibility to send different subscriptions of different information 

If we are going to keep TransportationStatusTypeCode there is a need for an listID

**Comment by agrindst** [comment]
@PeterLBorresen : Check for optional ListID

**Comment by PeterLBorresen** [comment]
Done

**Comment by agrindst** [comment]
As discussed in WG, we will make TransportationStatusTypeCode mandatory

**Please complete this action after internal review**
