### ISSUE TITLE
Correct misspelling Waybill 

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#109]
Please correct misspelling in this description: 

"The date when **thus** version of the waybill is issued"

I suppose it should be: 

"The date when **this** version of the waybill is issued"

https://test-docs.peppol.eu/logistics/waybill/syntax/Waybill/cbc-IssueDate/

**Comment by agrindst** [comment]
Please also look into this: 
"Free-form text pertinent to this shipment, **conveying** information that is not contained explicitly in other structures."

I think the right way to write this is: 
"Free-form text pertinent to this shipment, **conveys** information that is not contained explicitly in other structures."

https://test-docs.peppol.eu/logistics/waybill/syntax/Waybill/cac-Shipment/cbc-Information/

**Comment by PeterLBorresen** [comment]
done, the shipment information is the UBL information. If you are correct, we should update UBL as well. I  can make an issue on this but would like to dobbelt chck it first.

**Comment by agrindst** [comment]
Closing this issue, as there is no need for the last correction
