### ISSUE TITLE
OriginalDepartureCountry and FinalDestinationCountry

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#110]
There has been raised a question about the need for OriginalDepartureCountry and FinalDestinationCountry 

https://test-docs.peppol.eu/logistics/waybill/syntax/Waybill/cac-Shipment/cac-Consignment/cac-OriginalDepartureCountry/ 
https://test-docs.peppol.eu/logistics/waybill/syntax/Waybill/cac-Shipment/cac-Consignment/cac-FinalDestinationCountry/

OriginalDepartureCountry and FinalDestinationCountry is present in Waybill, TransportExecutionPlan, and TransportExecutionPlanRequest. 
We have decided to keep customs clearance out of scope, and the question is whether there is still a need for this information. 

Peter is looking into this issue, and trying to get information on what specific this information is used for, or if there are any specific use cases.

**Comment by agrindst** [comment]
Include OriginalDepartureCountry and FinalDestinationCountry
We need to describe use cases

**Comment by PeterLBorresen** [comment]
I think the descriptions are ok

**Comment by agrindst** [comment]
As desidered ok, closing this issue
