### ISSUE TITLE
Correct Text Waybill 

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#111]
In the document Copy of waybill comments second version the description text under Description was marked. 

https://test-docs.peppol.eu/logistics/waybill/syntax/Waybill/cac-Shipment/cac-Consignment/cac-TransportHandlingUnit/cac-GoodsItem/

Actions: 

- [x] Please correct this thext 
"A textual descript this goods item."

**Comment by agrindst** [comment]
Please also look into this: 

- [ ] fix the description text of Item: 
"Description of the product beeing transported. Used for a structurel description of the **item.** mandatory for Hazardous items." 

I think the . after item should not be there? 

https://test-docs.peppol.eu/logistics/waybill/syntax/Waybill/cac-Shipment/cac-Consignment/cac-TransportHandlingUnit/cac-GoodsItem/

**Comment by agrindst** [comment]
- [ ] please correct description text for CompanyID: 
https://test-docs.peppol.eu/logistics/waybill/syntax/Waybill/cac-Shipment/cac-Delivery/cac-DeliveryParty/cac-PartyLegalEntity/

**Comment by PeterLBorresen** [comment]
Done
