### ISSUE TITLE
Remove Amont from Payment Terms 

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#113]
From comment resolution: 
The amount is normally not known, and if it is, the Transport Service Provider will anyway ignore it and calculate it in their own system.

Please complete following actions: 

- [ ] remove Amount from Payment Terms

**Comment by PeterLBorresen** [comment]
Done. Removed Amount from Transport Execution plan request

**Comment by agrindst** [comment]
amount is removed fro payment terms
