### ISSUE TITLE
Remove Quantity, and add NetWeight in HazardousItem

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#114]
From comments under internal review period: 

The quantity is used only when Hazardous items are specified. Better to use the Net Weight in the group HazardousItem instead of the Quantity here. 

Please complete following actions: 

Transport Execution Plan Request: 
- [x] remove Quanitty in HazardousItem
- [x] add NetWeight in HazardousItem 

Transport Execution Plan: 
- [x] remove Quanitty in HazardousItem
- [x] add NetWeight in HazardousItem

**Comment by PeterLBorresen** [comment]
Not found Quantity in HazardousItem, but I think you mean Quantity in GoodsItem

**Comment by JorgenErlandsson** [comment]
WP0 is now fixed.

**Comment by agrindst** [comment]
@PeterLBorresen please verify this issue and check if this is compleeted
