### ISSUE TITLE
make a better description of how to use the different parts of the GoodsItem groups 

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#115]
From comments from internal review period: 

Since normally only the element Description will be used and all other elements only in specific cases, these specific cases need to be described, also in the BIS (which I have not checked).

**Comment by PeterLBorresen** [comment]
Nothing done in the structure. Needs further explaination of what is missing here. I can see a need in the BIS documents

**Comment by agrindst** [comment]
@PeterLBorresen will provide some descriptions and text to the BIS document

**Comment by PeterLBorresen** [comment]
Ok, Are. I will suggest that we make a section 6.8: GoodsItem.
GoodsItems desrcibes on need to know basis the goods being transported. It can be identified with a tekstual description or item containing the commodity classification and the hazardous item description. If the goods is hazardous then the goods item must be specified with a text.

**Comment by areberg** [comment]
Description added. Issue will be closed.
