### ISSUE TITLE
Add elements in TransportEvent

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#121]
Add the following elements/groups in TransportEvent:      
https://test-docs.peppol.eu/logistics/transportation-status/syntax/TransportationStatus/cac-TransportEvent/                                                                            

- [x]  TransportEventTypeCode                                                                

- [x]  CompletionIndicator                                                                                

- [x] CurrentStatus (ConditionCode, Description, StatusReasonCode, StatusReason)

**Comment by PeterLBorresen** [comment]
Done. Added listID til Status Reason Code as mandatory
