### ISSUE TITLE
	cac:MainTransportationService should be mandatory in transport execution plan

### ISSUE THREAD

**Issue by PeterLBorresen** [OpenPEPPOL/logistics-bis#122]
cac:MainTransportationService should be mandatory in transport execution plan so it is obvious whether to specify this one or additional transportation services

**Comment by agrindst** [comment]
@PeterLBorresen: please implement this change

**Comment by PeterLBorresen** [comment]
Done

**Comment by agrindst** [comment]
closed as completed
