### ISSUE TITLE
AllowanceChargeReasonCode is missing a code list

### ISSUE THREAD

**Issue by PeterLBorresen** [OpenPEPPOL/logistics-bis#126]
AllowanceChargeReasonCode is missing a code list. Create a default code list and add list ID (optional) to the code.

**Comment by agrindst** [comment]
@PeterLBorresen please implement this change

**Comment by PeterLBorresen** [comment]
Corrected in Transport Execution Plan and Transport Execution Plan Request

**Comment by agrindst** [comment]
actions: 

- [ ] Complete also for waybill

**Comment by PeterLBorresen** [comment]
Consignment in Waybill does not contrain AllowanceCharge, see https://test-docs.peppol.eu/logistics/waybill/syntax/Waybill/cac-Shipment/cac-Consignment/ Do you suggest to add?

**Comment by agrindst** [comment]
Since AllowanceCharge is not in waybill, this is not implemented in this version
