### ISSUE TITLE
Estimated Despatch period is missing in Waybill

### ISSUE THREAD

**Issue by areberg** [OpenPEPPOL/logistics-bis#129]
The date is present on the CMR document.

**Comment by agrindst** [comment]
@PeterLBorresen  please add EstimatedDespatchPeriod

**Comment by PeterLBorresen** [comment]
Done

**Comment by areberg** [comment]
@PeterLBorresen Must be changed from cac:EstimatedDeliveryPeriod to cac:EstimatedDespatchPeriod.

**Comment by PeterLBorresen** [comment]
Done
