### ISSUE TITLE
Update BIS document for Advanced Despatch Advice Only

### ISSUE THREAD

**Issue by JorgenErlandsson** [OpenPEPPOL/logistics-bis#130]
The following updates are needed:
-  Use-case 7 and 8 modified. Also the example files need to be updated.
-  Use-case 9, 10 and 11 need to be added, and the corresponding example files.
-  Section 6.6, Delivery Dateneed to be updated so that ActualDeilveryDate and ...Time also are listed.
-  Section 6.8.1 Fuel have some editorial small things to fix.
-  Section 6.8.2 Environmental Emission - same.
-  Section 6.8.3 Product Climate Data - some additional descriprion is needed.

**Comment by JorgenErlandsson** [comment]
@areberg : I (Jörgen) can do the modifications since I know which they are. Assigned it to you for decision.

**Comment by areberg** [comment]
Please do the updates @JorgenErlandsson
