### ISSUE TITLE
PartyIdentification and PartyName

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#131]
There is an ongoing discussion regarding wether PartyName or PartyIdentification shall be mandatory, or if they should both be optional and then create a rule that one of the needs to be provided. 

**Are and Rickard will adress this in the next Peppol-meeting.**

This issue was adressed when discussing : 
Advaced Despatch Advice, and Advanced Despatch Advice with Response: 
- DespatchSupplierParty 
- DeliveryCustomerParty
- CarrierParty
- DespatchLine/Item/ManufacturerParty

and Weight Statement: 

- SenderParty 
- SenderParty/PartyIdentification/ID/@schemeID 
- ReceiverParty/PartyIdentification/ID/@schemeID 
- ReceiverParty
- WeighingParty/PartyIdentification/ID/@schemeID 
- WeighingParty
- ShipperParty/PartyIdentification/ID/@schemeID 
- ShipperParty

Receipt advice version 1.0:

- DespatchSupplierParty
- DeliveryCustomerParty
- CarrierParty

**Comment by agrindst** [comment]
Keep both optional, create a rule that one of them needs to be provided

**Comment by PeterLBorresen** [comment]
Is a rule needed or is it just an recommendation? PartyLegalEntity is mandatory

**Comment by areberg** [comment]
I think we agreed to have a rule.

**Comment by agrindst** [comment]
Agreed to have both optional and create a rule that one of them must be provided. 

please complete for all formats

- [ ] Advanced Despatch Advice
- [ ] Weight statement
- [ ] Transport Execution plan Request
- [ ] Transport Execution Plan 
- [ ] Waybill 
- [ ] Transportation status Request
- [ ] Transportation status 
- [ ] Receipt advice

**Comment by JorgenErlandsson** [comment]
T120, T122 and T128 now fixed.
Rules created, added into the message documentation, unit-tests created.

**Comment by agrindst** [comment]
@PeterLBorresen

**Comment by agrindst** [comment]
compleeted
