### ISSUE TITLE
Corrections, Advanced Despatch Advice version 1.2

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#132]
Decided actions from 
[WP0_WP4.docx](https://github.com/OpenPEPPOL/logistics-bis/files/11724942/WP0_WP4.docx)
 and as discussed in WG-meeting

Actions:

- [x] ProfileID:Correct the description . Replace “…w_response” with “…w_receipt_advice”.
- [x] AdditionalDocumentReference:Correct the descrition, Remove “BEAst”.
- [x] Shipment/GrossVolumeMeasure: Correct the description.
- [x] CarrierParty/PostalAddress: Add Name and Description for the whole group.
- [x] ActualDeliveryDate and …Time: Add in description that they are used only when ADA is sent after delivery.
- [x] EstimatedDeliveryPeriod: Add in description that this group is used only when ADA is sent before delivery.
- [x] EstimatedDeliveryPeriod/StartDate: Suggest that we change cardinality to Optional.
- [ ] Shipment/Delivery/Despatch/DespatchAddress: Suggest that we add element Name.
- [x] Shipment/TransportHandlingUnit/TransportHandlingUnitTypeCode: Remove “Retursystem byggpall” from description.
- [x] Codelist ItemPropertyNameCode should be updated

**Comment by JorgenErlandsson** [comment]
All changes except one is done. Please keep issue open for now.

**Comment by JorgenErlandsson** [comment]
This is now done. Issue can be closed
