### ISSUE TITLE
Add rule, and look into codelist 

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#134]
From comments to WP 0 and 4: 
WeighingParty/PhysicalLocation: Add a rule that ID or Name must exist.

As decided in work group; 

- [x] Jörgen will look into possible code lists 
- [x] add a rule that either ID or Name must be provided

**Comment by JorgenErlandsson** [comment]
Suggest that we do not use any Codelist for WeighingParty/PhysicalLocation/ID/@schemeID.
Should we decide to do use a codelist, it should be ICD as for other PartyIdentification/ID. But then it will not be possible to use schemeID if the issuer is not in that list and information about who issued the ID is lost.

**Comment by JorgenErlandsson** [comment]
Rule is now added. Issue can be closed if we omit the codelist as suggested.
