### ISSUE TITLE
Rules:  AdditionalDocumentReference/DocumentType and /DocumentTypeCode

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#135]
[WP0_WP4.docx](https://github.com/OpenPEPPOL/logistics-bis/files/11725060/WP0_WP4.docx)

Actions: 
 **For Advanced despatch advice 1.2:** 
- [x] add a rule that either AdditionalDocumentReference/DocumentType or /DocumentTypeCode must be provided 
- [x] add a description that one of these must be provided 
and: 
- [x] add a rule that either DocumentReference/DocumentType or /DocumentTypeCode must be provided 
- [x] add a description that one of these must be provided 

**For Receipt Advice version 1.0:** 
- [x] add a rule that either AdditionalDocumentReference/DocumentType or /DocumentTypeCode must be provided 
- [x] add a description that one of these must be provided

**Comment by JorgenErlandsson** [comment]
Issue 135 is fixed and can be closed
