### ISSUE TITLE
Waybill: rule, Transport Means 

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#140]
A suggested rule was addressed in WG-meeting. There is a need for further investigation whether to include or how to solve this issue. 

Suggestion: 

10.	The Transport means has to be specified according to the selected transport mode code
`a.`	If the transport ode code is 3 then shipment/cac:ShipmentStage/cac:TransportMeans/RoadTransport is mandatory (and the others should not be there)
`b.`	If the transport means code is 1 then shipment/cac:ShipmentStage/cac:TransportMeans/MaritimeTransport is mandatory (and the others should not be there)
`c.`	If the transport means code is 4 then shipment/cac:ShipmentStage/cac:TransportMeans/AirTransport is mandatory (and the others should not be there)
`d.`	If the transport means code is 2 then shipment/cac:ShipmentStage/cac:TransportMeans/RailTransport is mandatory (and the others should not be there)

There was also a suggestion to write a description, and not create a rule. WG decided to look into posibilities.

**Comment by PeterLBorresen** [comment]
done
