### ISSUE TITLE
Correct misspelling occurrence

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#145]
Occurrence is written "Occurence" in the description fields of OccurrenceDate and OccurrenceTime. 

please correct this misspelling for both: 
- [x] OccurrenceDate
- [ ] OccurrenceTime

https://test-docs.peppol.eu/logistics/qa/syntax/TransportationStatus/cac-Consignment/cac-TransportEvent/

**Comment by PeterLBorresen** [comment]
Done

**Comment by areberg** [comment]
Verified OK
