### ISSUE TITLE
Update addresses in Weight Statement

### ISSUE THREAD

**Issue by PeterLBorresen** [OpenPEPPOL/logistics-bis#146]
The Weight Statement does not follow the same pattern as the other documents in Peppol Logistics whgen it comes to adress. Proposed to change.

**Comment by JorgenErlandsson** [comment]
I suggest that we do not add Tax and Legal information to this message. Other changes, like adding address, are ok.
This message is just a verification of how much something weighs, not any legal document.

**Comment by agrindst** [comment]
agree to the suggested solution

**Comment by JorgenErlandsson** [comment]
This is now solved and issue can be closed
