### ISSUE TITLE
Timezone 

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#149]
Add timezone in all formats: 

- [x] Add timezone in Advanced Despatch Advice - optional 
- [x] Add timezone in Weight statement -  mandatory 
- [x] add timezone in Transport Execution plan and Transport Executionplan request - mandatory 
- [x] Add timezone in Waybill - mandatory 
- [x] Add timezone in transportation status and transportation status request - mandatory
- [x] Add timezone in receipt advice - optional

**Comment by JorgenErlandsson** [comment]
I have not found a way to specify if TimeZone is Mandatory or Optional.
I have implemented this in the WeightStatement so that I have created a rule (fatal) to check if timezone is included or not.
When TimeZone is optional I will leave the rule out.

If anyone knows how to define it mandatory/optional, please let me know.

**Comment by JorgenErlandsson** [comment]
One more question.
We have today a set of business rules that we use on periods that include fron/to date/time. Because we added the timezone these rules need to be updated. Does anybody know how? I do not have a clue how to create rules that include calculation of time based on the zone.

**Comment by JorgenErlandsson** [comment]
WP0 + WP4 done (except the rules....)

**Comment by agrindst** [comment]
@PeterLBorresen do you know of any solutions for what Jörgen is commenting about developing rules for formats with mandatory Timezone?

**Comment by PeterLBorresen** [comment]
Added in the structure. Will develope rules for checking its present.

**Comment by PeterLBorresen** [comment]
Added valudation for present of timezone. The trick is to check for prenset of "-", "+", "z" or "Z". The XSD validation check for the rest.
