### ISSUE TITLE
Change description l ItemSerialID

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#151]
As discussed in WG - meeting please change/adjust the description. 

https://test-docs.peppol.eu/logistics/qa/syntax/AdvancedDespatchAdvice/cac-DespatchLine/cac-Item/cac-ItemInstance/cbc-SerialID/ 

today the description is: "Serial numbers for items listed in the dispatch line."

the comment from the comment resolution was that: 
"It is important to refer a specific ItemInstance using an ID in other tag of the document (such as cac:GoodsItem/cbc:ID - see Ref. 4)" 

we concluded that we shall not implement this change, however we saw the need to change the descritpion.

**Comment by JorgenErlandsson** [comment]
This is now changed and issue can be closed
