### ISSUE TITLE
Create usecase description of multiple ItemInstance for one DespatchLIne

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#152]
From comment resolution and WG-meeting this week desided that there is a need for uscase description for multiple ItemInstance for one batch with the same attributes. The TraceID can be used to point at one of the specifically ItemInstances by using the SerialID. 

actions: 

- [x] create usecase description for a usecase with multiple ItemInstance in one DespatchLine

**Comment by JorgenErlandsson** [comment]
Usecase 12 created in BIS together with a new example file. Issue can be closed.
