### ISSUE TITLE
Bug Fixing Receipt Advice 

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#154]
From comment resolution there were a few bugs idenitified. Please fixt these bugs by completing these actions: 

- [x] correct the description by inserting "Receipt Advice" and remove "Despatch Advice"

> - [x] description IssueDate l https://test-docs.peppol.eu/logistics/qa/syntax/ReceiptAdvice/cbc-IssueDate/ 

> - [x] description IssueTime l https://test-docs.peppol.eu/logistics/qa/syntax/ReceiptAdvice/cbc-IssueTime/ 

> - [x] dispatch Note "Dispatch note " https://test-docs.peppol.eu/logistics/qa/syntax/ReceiptAdvice/ 

- [x] change element name from DocumentDescription to DocumentStatusDescription to reffer to the status of the Despatch Document  https://test-docs.peppol.eu/logistics/qa/syntax/ReceiptAdvice/cac-DespatchDocumentReference/cbc-DocumentDescription/ 
- [x] change the description of Consignment/cbc:ID https://test-docs.peppol.eu/logistics/qa/syntax/ReceiptAdvice/cac-Shipment/cac-Consignment/cbc-ID/ today the description is "use a dummy value since this element is mandatory" this is only true for Receipt Advice that is not related to goods. 
- [x] remove RequestedDeliveryPeriod 
- [x] change cardinality of Status under TransportHandlingunit to 1..1 https://test-docs.peppol.eu/logistics/qa/syntax/ReceiptAdvice/cac-Shipment/cac-TransportHandlingUnit/cac-Status/
- [x] change the description of DespatchLineReference/cbc:ID. insert the use of "NS-dummy value" for specific situations. there could be goods shipped that is not present in a Despatch Advice https://test-docs.peppol.eu/logistics/qa/syntax/ReceiptAdvice/cac-ReceiptLine/cac-DespatchLineReference/

**Comment by JorgenErlandsson** [comment]
These are now done and issue can be closed.
