### ISSUE TITLE
Insert elements to Advanced Despatch Advice 

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#155]
As decided in PG, and from comment resolution please insert following elements: 

- [x] insert following elements in SellserSupplyerParty:
```
- The structure cac:PartyTaxScheme, the fields cbc:CompanyID e cac:TaxScheme/cbc:ID;
- The structure cac:PartyLegalEntity, the fields cbc:RegistrationName, cbc:CompanyID; the structure cac:RegistrationAddress and the fields cbc:CityName, cac:Country/cbc:IdentificationCode;
- The structure cac:Contact and the fields cbc:Name, cbc:Telephone and cbc:ElectronicMail.
```

- [x] Insert following elements in CarrierParty:
```
- The structure cac:PartyTaxScheme, the fields cbc:CompanyID e cac:TaxScheme/cbc:ID;
- The structure cac:PartyLegalEntity, the fields cbc:RegistrationName, cbc:CompanyID; the structure cac:RegistrationAddress and the fields cbc:CityName, cac:Country/cbc:IdentificationCode;
- The structure cac:Contact and the fields cbc:Name, cbc:Telephone and cbc:ElectronicMail.
```

- [x] insert following elements in CarrierParty:
 ```
- The structure cac:PostalAddress and the fields cbc:StreetName, cbc:AdditionalStreetName, cbc:CityName, cbc:PostalZode, cbc:CountrySubentity; the structure cac:AddressLine and the field cbc:Line and the structure cac:Country and the field cbc:IdentificationCode;
- The structure cac:PartyTaxScheme, the field cbc:CompanyID and cac:TaxScheme/cbc:ID;
- The structure cac:PartyLegalEntity, the fields cbc:RegistrationName, cbc:CompanyID; the structure cac:RegistrationAddress and the fields cbc:CityName, cac:Country/cbc:IdentificationCode;
- The structure cac:Contact and the fields cbc:Name, cbc:Telephone and cbc:ElectronicMail.
```

- [ ] insert following elements in OrderReference 
`CustomerReference, cardinality 0..1`

**Comment by JorgenErlandsson** [comment]
Changes on the Parties were made earlier based on another issue.

Change on OrderReference I do not remember. When did we decide that and what should it be used for?

**Comment by agrindst** [comment]
You are completely right. 
I have written it not correctly. 


About OrderReference: 
The suggestion was to add CustomerReference in the header (outside OrerReference) in UBL2.4 Until UBL2.4 has been released the solution is to use AdditionalDocumentReference instead. 


As of my understanding we can then consider this issue to be compleeted, can you confirm @JorgenErlandsson?

**Comment by JorgenErlandsson** [comment]
Yes, it can be closed.

Jörgen Erlandsson
Senior consultant.
***@***.***
E-mail: ***@***.******@***.***>
Phone: +46 (0)70 67 514 01
tyringe.com<https://tyringe.com/>   Follow us on LinkedIn!<https://www.linkedin.com/company/tyringekonsult-ab/>
Support: +46 (0)451 570 70
E-mail: ***@***.******@***.***>

Från: agrindst ***@***.***>
Skickat: den 28 juni 2023 11:00
Till: OpenPEPPOL/logistics-bis ***@***.***>
Kopia: Jörgen Erlandsson,Tyringe ***@***.***>; Mention ***@***.***>
Ämne: Re: [OpenPEPPOL/logistics-bis] Insert elements to Advanced Despatch Advice (Issue #155)


You are completely right.
I have written it not correctly.

About OrderReference:
The suggestion was to add CustomerReference in the header (outside OrerReference) in UBL2.4 Until UBL2.4 has been released the solution is to use AdditionalDocumentReference instead.

As of my understanding we can then consider this issue to be compleeted, can you confirm @JorgenErlandsson<https://github.com/JorgenErlandsson>?
