### ISSUE TITLE
Change Cardinality in Advanced Despatch Advice 

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#157]
Decisions made in Project group, after the internal review period. Please complete these actions: 

- [x] change the cardinality of Shimpent to 1..1  https://test-docs.peppol.eu/logistics/qa/syntax/AdvancedDespatchAdvice/cac-Shipment/
- [x] change the cardinality of @listID to M

**Comment by JorgenErlandsson** [comment]
This was done earlier based on another issue. Can be closed.
