### ISSUE TITLE
CarrierParty is missing in TransportExecutionPlan MainCarriageShipmentStage

### ISSUE THREAD

**Issue by PeterLBorresen** [OpenPEPPOL/logistics-bis#160]
It is present in PreCarriageShipmentStage and OncarriageShipmentStage

**Comment by agrindst** [comment]
Actions: 

- [ ] Add CarrierParty as optional  

@PeterLBorresen

**Comment by JorgenErlandsson** [comment]
The added Carrier group is missing the Identity. Same issue is on Carrier in Pre-Carriage and On-Carriage groups.

**Comment by areberg** [comment]
All ID's updated
