### ISSUE TITLE
Create a rule about consistensy of weight and volume between line level and header level 

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#165]
Create a rule about not being able to check that the sum of either Weight og Volume at line level i consistent with the sum at the header level when there is used different unit measures. Example: Kg or tons. 

actions: 
create this rule for both Weight and Volume 

- [x] Advanced Despatch Advice
- [x] Weight statement 
- [x] Transport Execution Plan Request
- [x] Transport Execution Plan 
- [x] Waybill 
- [x] Transportation Status Request
- [x] Transportation Status
- [x] Receipt advice

**Comment by JorgenErlandsson** [comment]
ADA, RA and WeightStatement are now ok. Changes required only in ADA.
Information about the change made is copied to Peter so that the rule change not must be "invented" again.

**Comment by agrindst** [comment]
- [ ] Add desimals in unit test for weight

**Comment by JorgenErlandsson** [comment]
Rules now updated for TEPR, TEP and Waybill also. TSR and TS - no change needed.
