### ISSUE TITLE
Wrong Delivery Terms in Advanced Despatch Advice Use Case 2

### ISSUE THREAD

**Issue by PeterLBorresen** [OpenPEPPOL/logistics-bis#167]
There seems to be a copy paste error in Advanced Despatch Advice Use Case 2. In the BIS description it says:

Despatch Advice for transport of goods (not bulk goods) where the Supplier is responsible for transportation.
In the example it is EXW, I propose to change it to DAP (delivered at place), which could be a logical agreement for such a short tour for plaster boards.

**Comment by JorgenErlandsson** [comment]
Changes according to request. However, the same "problem" can exist also for other use-cases since they all are created  as copies of other examples. 
Anyway - issue can now be closed.
