### ISSUE TITLE
QA l Name spelling 

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#169]
Excel document: 

[Peppol Logistics l QA l forbokstaver på format-navn l Alle formater.xlsx](https://github.com/OpenPEPPOL/logistics-bis/files/11956842/Peppol.Logistics.l.QA.l.forbokstaver.pa.format-navn.l.Alle.formater.xlsx)

**`Actions: Correct Name spelling`** 

**Advanced Despatch Advice:** 

- [x] Description Text under IssueDate "the date when **the advaced despatch advice** is...." https://test-docs.peppol.eu/logistics/qa/syntax/AdvancedDespatchAdvice/cbc-IssueDate/

- [x] description text under IssueTime "The time when **the advanced despatch advice**..."https://test-docs.peppol.eu/logistics/qa/syntax/AdvancedDespatchAdvice/cbc-IssueTime/ 

**Weight Statement:** 

- [x] Descritpion Text under ID "Unique identity identifying **the weight statement**." https://test-docs.peppol.eu/logistics/qa/syntax/WeightStatement/cbc-ID/ 

- [x] Description text under IssueDate "The date when **the weight statement** is issued." https://test-docs.peppol.eu/logistics/qa/syntax/WeightStatement/cbc-IssueDate/ 

- [x] The headliner above the descritption text of IssueDate "**Weight statement** issue date" https://test-docs.peppol.eu/logistics/qa/syntax/WeightStatement/ 

- [x] the headliner above the description text of IssueTime "**Weight statemen**t type code" https://test-docs.peppol.eu/logistics/qa/syntax/WeightStatement/ 

- [x] the headliner above the description text of WeightStatementTypeCode "**Weight statement** type code" https://test-docs.peppol.eu/logistics/qa/syntax/WeightStatement/ 

- [x] Description text under SenderParty "The party sending this **weight statement**" https://test-docs.peppol.eu/logistics/qa/syntax/WeightStatement/cac-SenderParty/

- [x] Description text under ReceiverParty "The party receiving **this weight statement**" https://test-docs.peppol.eu/logistics/qa/syntax/WeightStatement/cac-ReceiverParty/ 

**Transport Execution Plan Request** 

- [x] the headliner above the description text of DocumentStatusCode "**Transport execuition plan request** status code" https://test-docs.peppol.eu/logistics/qa/syntax/TransportExecutionPlanRequest/ 

**Transport Execution Plan** 

- [x] the headliner above the description text of DocumentStatusCode "**Transport execuition plan request** status code" https://test-docs.peppol.eu/logistics/qa/syntax/TransportExecutionPlan/ 

- [x] the description text under TransportUserRemarks " Not used in **the transport execution plan** only profile" https://test-docs.peppol.eu/logistics/qa/syntax/TransportExecutionPlan/cbc-TransportUserRemarks/

- [x] the description text under TransportExecutionPlanRequestDocumentReference "Reference to a **transport execution plan request.** " https://test-docs.peppol.eu/logistics/qa/syntax/TransportExecutionPlan/cac-TransportExecutionPlanRequestDocumentReference/ 

- [x] the description text under IssueDate "The Issue Date when **the transport execution plan request** was issued" https://test-docs.peppol.eu/logistics/qa/syntax/TransportExecutionPlan/cac-TransportExecutionPlanRequestDocumentReference/cbc-IssueDate/

- [x] the description time under IssueTime "The Issue time when **the transport execution plan request** was issued" https://test-docs.peppol.eu/logistics/qa/syntax/TransportExecutionPlan/cac-TransportExecutionPlanRequestDocumentReference/cbc-IssueTime/ 

- [x] the description text under AdditionalDocumentReference "Reference to additional documents relevant for **this transport execution plan.**" https://test-docs.peppol.eu/logistics/qa/syntax/TransportExecutionPlan/cac-AdditionalDocumentReference/ 

- [x] the description text under ConsigneeParty "The party responsible for receiving the goods in the **transport execution plan.** "https://test-docs.peppol.eu/logistics/qa/syntax/TransportExecutionPlan/cac-Consignment/cac-ConsigneeParty/ 

- [x] the description text under ConsignorParty "The party responsible for sending the goods in **the transport execution plan.**" https://test-docs.peppol.eu/logistics/qa/syntax/TransportExecutionPlan/cac-Consignment/cac-ConsignorParty/ 

**Waybill** 

- [x] the description text under IssueDate  "The date when this version of the waybill is issued" https://test-docs.peppol.eu/logistics/qa/syntax/Waybill/cbc-IssueDate/ 

- [x] the description text under IssueTime  "The time when this version of **the waybill** is issued." https://test-docs.peppol.eu/logistics/qa/syntax/Waybill/cbc-IssueTime/ 

- [x] the description text under Name  "The name (kind of **waybill)** of **waybill** type. Use "CMR" for CMR, "Bill of Laden" for Bill of laden, "Air **waybil**l" for Air **waybill** or CIM for Train **waybill.** "  https://test-docs.peppol.eu/logistics/qa/syntax/Waybill/cbc-Name/

- [x] the description text under ConsignorParty  "The party sending the goods in the **waybill,** often the issuer of **the waybill.** " https://test-docs.peppol.eu/logistics/qa/syntax/Waybill/cac-ConsignorParty/ 

- [x] the description text under CarrierParty  "The carrier party responsible for this **waybill.** " https://test-docs.peppol.eu/logistics/qa/syntax/Waybill/cac-CarrierParty/

- [x] the description text under Shipment  "The shipment for this **waybill.**" https://test-docs.peppol.eu/logistics/qa/syntax/Waybill/cac-Shipment/

- [x] the description text under ConsigneeParty  "The party responsible for receiving the goods in **waybill**. " https://test-docs.peppol.eu/logistics/qa/syntax/Waybill/cac-Shipment/cac-Consignment/cac-ConsigneeParty/

- [x] the description text under ShipmentStage  "The shipment stage for this **waybill**. " https://test-docs.peppol.eu/logistics/qa/syntax/Waybill/cac-Shipment/cac-ShipmentStage/ 

- [x] the description text under DocumentReference  "Reference to documents relevant for **this waybill**. " https://test-docs.peppol.eu/logistics/qa/syntax/Waybill/cac-DocumentReference/

- [x] the description text under Signature  "A signature applied to this **waybill**. " https://test-docs.peppol.eu/logistics/qa/syntax/Waybill/cac-Signature/

- [x] the description text under SignatoryParty  "The party signing this **waybill**. " https://test-docs.peppol.eu/logistics/qa/syntax/Waybill/cac-Signature/cac-SignatoryParty/

**Transportation Status Request** 

- [x] the description text under IssueTime  "The time when **the transportation status request** was issued. " https://test-docs.peppol.eu/logistics/qa/syntax/TransportationStatusRequest/cbc-IssueTime/

- [x] the description text under IssueDate  "The date when **the transporation status request** was issued. " https://test-docs.peppol.eu/logistics/qa/syntax/TransportationStatusRequest/cbc-IssueDate/

- [x] #173

- [x] #174

- [x] the description text under SenderParty  "The party sending **the transportation status request**. " https://test-docs.peppol.eu/logistics/qa/syntax/TransportationStatusRequest/cac-SenderParty/ 

- [x] the description text under ReceiverParty  "The party receiving **the transportation status request**. "  https://test-docs.peppol.eu/logistics/qa/syntax/TransportationStatusRequest/cac-ReceiverParty/

- [x] the description text under TransportExecutionPlanDocumentReference  "Reference to a **transport execution plan**. " https://test-docs.peppol.eu/logistics/qa/syntax/TransportationStatusRequest/cac-TransportExecutionPlanDocumentReference/

- [x] the description text under IssueDate  "The Issue Date when the **transport execution plan reques**t was issued " https://test-docs.peppol.eu/logistics/qa/syntax/TransportationStatusRequest/cac-TransportExecutionPlanDocumentReference/cbc-IssueDate/ 

- [x] the description text under IssueTime  "The Issue time when the **transport execution plan request** was issued " https://test-docs.peppol.eu/logistics/qa/syntax/TransportationStatusRequest/cac-TransportExecutionPlanDocumentReference/cbc-IssueTime/ 

- [x] the description text under Consignment "The consignment related to **this transportation status.**" https://test-docs.peppol.eu/logistics/qa/syntax/TransportationStatusRequest/cac-Consignment/

**Comment by JorgenErlandsson** [comment]
T120 and T122 are now fixed.

**Comment by agrindst** [comment]
**Transportation Status** 

- [ ] the description text under IssueTime "The time when **the transportation statu**s was issued." https://test-docs.peppol.eu/logistics/qa/syntax/TransportationStatus/cbc-IssueTime/

- [ ] the description text under Description "Textual description of the **Transportation status**." https://test-docs.peppol.eu/logistics/qa/syntax/TransportationStatus/cbc-Description/

- [ ] the description text under TransportationStatusTypeCode "The type of **the transportation status** code. Mandatory if **the transportation status** is an answer to **a transportation status request.**" https://test-docs.peppol.eu/logistics/qa/syntax/TransportationStatus/cbc-TransportationStatusTypeCode/


- [ ] the description text under Consignment "The consignment related to this **transportation status.**" https://test-docs.peppol.eu/logistics/qa/syntax/TransportationStatus/cac-Consignment/


- [ ] the description text under TransportEvent "A transport event associated to **this transportation status.** " https://test-docs.peppol.eu/logistics/qa/syntax/TransportationStatus/cac-Consignment/cac-TransportEvent/ 


- [ ] the description text under TransportHandlingUnit "The transport handling unit refered to in this **transportation status.** " https://test-docs.peppol.eu/logistics/qa/syntax/TransportationStatus/cac-Consignment/cac-TransportHandlingUnit/


- [ ] the description text under DocumentReference "Reference to additional documents relevant for this **transportation status** such as picktures of damages. " https://test-docs.peppol.eu/logistics/qa/syntax/TransportationStatus/cac-DocumentReference/


- [ ] the description text under Signature "A signature applied to this **transportation status**. " https://test-docs.peppol.eu/logistics/qa/syntax/TransportationStatus/cac-Signature/

- [ ] the description text under SignatoryParty "The party signing this **transportation status** " https://test-docs.peppol.eu/logistics/qa/syntax/TransportationStatus/cac-Signature/cac-SignatoryParty/

- [ ] the description text under TransportEvent "A transport event related to thist **transportation status**." https://test-docs.peppol.eu/logistics/qa/syntax/TransportationStatus/cac-TransportEvent/ 

- [ ] Misspelling the description text under TransportEvent "A transport event related to **thist** transportation status." https://test-docs.peppol.eu/logistics/qa/syntax/TransportationStatus/cac-TransportEvent/ 

- [ ] the description text under Signature "A signature applied to this **transportation status**. " https://test-docs.peppol.eu/logistics/qa/syntax/TransportationStatus/cac-TransportEvent/cac-Signature/

- [ ] the description text under SignatoryParty "The party signing **this transportation status.** "  https://test-docs.peppol.eu/logistics/qa/syntax/TransportationStatus/cac-TransportEvent/cac-Signature/cac-SignatoryParty/

- [ ] the description text under SenderParty "The party sending **the transportation status.** " https://test-docs.peppol.eu/logistics/qa/syntax/TransportationStatus/cac-SenderParty/ 

- [ ] the description text under ReceiverParty "The party receiving **the transportation status.** " https://test-docs.peppol.eu/logistics/qa/syntax/TransportationStatus/cac-ReceiverParty/

- [ ] the description text under TransportationStatusRequestDocumentReference "Reference to a **transport execution plan**. " https://test-docs.peppol.eu/logistics/qa/syntax/TransportationStatus/cac-TransportationStatusRequestDocumentReference/

- [ ] the description text under IssueDate "The **issue Date** when **the transport execution plan request** was issued" https://test-docs.peppol.eu/logistics/qa/syntax/TransportationStatus/cac-TransportationStatusRequestDocumentReference/cbc-IssueDate/

- [ ] the description text under IssueTime "The issue time when **the transport execution plan request** was issued" https://test-docs.peppol.eu/logistics/qa/syntax/TransportationStatus/cac-TransportationStatusRequestDocumentReference/cbc-IssueTime/


- [ ] the description text under TransportExecutionPlanDocumentReference "Reference to a **transport execution plan.** " https://test-docs.peppol.eu/logistics/qa/syntax/TransportationStatus/cac-TransportExecutionPlanDocumentReference/

- [ ] the description text under IssueDate "The Issue Date when **the transport execution plan request** was issued " https://test-docs.peppol.eu/logistics/qa/syntax/TransportationStatus/cac-TransportExecutionPlanDocumentReference/cbc-IssueDate/

- [ ] the description text under IssueTime "The Issue time when **the transport execution plan request** was issued " https://test-docs.peppol.eu/logistics/qa/syntax/TransportationStatus/cac-TransportExecutionPlanDocumentReference/cbc-IssueTime/



**Receipt Advice** 

- [ ] the description text under IssueDate "The date when **the receipt advice** was issued. " https://test-docs.peppol.eu/logistics/qa/syntax/ReceiptAdvice/cbc-IssueDate/

- [ ] the description text under IssueTime "The time when **the receipt advice** is issued. " https://test-docs.peppol.eu/logistics/qa/syntax/ReceiptAdvice/cbc-IssueTime/ 

- [ ] the headliner above description text under DocumentStatusCode "**Receipt advice** status code" https://test-docs.peppol.eu/logistics/qa/syntax/ReceiptAdvice/

- [ ] the headliner above description text under ReceiptAdviceTypeCode "**Receipt advice** type code" https://test-docs.peppol.eu/logistics/qa/syntax/ReceiptAdvice/


- [ ] the description text under AdditionalDocumentReference "Reference to additional documents relevant for **this Receipt advice**." https://test-docs.peppol.eu/logistics/qa/syntax/ReceiptAdvice/cac-AdditionalDocumentReference/

**Comment by agrindst** [comment]
@JorgenErlandsson please also see the last update with issues from Receipt Advice

**Comment by areberg** [comment]
Corrected TEPR, TEP, Waybill, TSR and TS.

**Comment by agrindst** [comment]
Actions left: 
2 in waybill, and 2 in transportation status. 

Have created own issues for the 2 in waybill, however I could not do the same for the 2 in transportation status. 
I have therefore reopened this issue

**Comment by areberg** [comment]
Since this is not the name of the transactions i didn't change these names. But looking at it again I will rewrite the description.

**Comment by agrindst** [comment]
compleeted
