### ISSUE TITLE
Business rules needs to have a usage

### ISSUE THREAD

**Issue by RikardLarsson-BEAst** [OpenPEPPOL/logistics-bis#170]
All business rules needs to have a context. 
Example that has a usage: 
https://test-docs.peppol.eu/logistics/qa/rules/PEPPOL-T120-R002/

Example that does not have a context:
https://test-docs.peppol.eu/logistics/qa/rules/PEPPOL-T124-R001/

The usage is given by adding a reference to the rule, e.g. 
`<cbc:CustomizationID>urn:fdc:peppol.eu:logistics:trns:advanced_despatch_advice:1<?Rule PEPPOL-T120-R011?></cbc:CustomizationID>`

If the rules has no usage it is difficult to develop by reading the syntax specification

**Comment by JorgenErlandsson** [comment]
Also would like to add that this pointer should be to the correct message. In example below there is a link between rule for T120 and Waybill.

PEPPOL-T120-R013
Message
EndTime cannot be specified without StartTime

Context
cac:EstimatedDeliveryPeriod
Test
not(cbc:EndTime) or (cbc:EndTime) and (cbc:StartTime)
Usage
[/ ](https://test-docs.peppol.eu/logistics/qa/rules/PEPPOL-T120-R013/syntax/AdvancedDespatchAdvice/cac-Shipment/cac-Delivery/cac-EstimatedDeliveryPeriod/cbc-StartTime/)[ubl:DespatchAdvice](https://test-docs.peppol.eu/logistics/qa/syntax/AdvancedDespatchAdvice/) / [cac:Shipment](https://test-docs.peppol.eu/logistics/qa/syntax/AdvancedDespatchAdvice/cac-Shipment/) / [cac:Delivery](https://test-docs.peppol.eu/logistics/qa/syntax/AdvancedDespatchAdvice/cac-Shipment/cac-Delivery/) / [cac:EstimatedDeliveryPeriod](https://test-docs.peppol.eu/logistics/qa/syntax/AdvancedDespatchAdvice/cac-Shipment/cac-Delivery/cac-EstimatedDeliveryPeriod/) / [cbc:StartTime](https://test-docs.peppol.eu/logistics/qa/syntax/AdvancedDespatchAdvice/cac-Shipment/cac-Delivery/cac-EstimatedDeliveryPeriod/cbc-StartTime/)
[/ ](https://test-docs.peppol.eu/logistics/qa/rules/PEPPOL-T120-R013/syntax/AdvancedDespatchAdvice/cac-Shipment/cac-Delivery/cac-EstimatedDeliveryPeriod/cbc-EndTime/)[ubl:DespatchAdvice](https://test-docs.peppol.eu/logistics/qa/syntax/AdvancedDespatchAdvice/) / [cac:Shipment](https://test-docs.peppol.eu/logistics/qa/syntax/AdvancedDespatchAdvice/cac-Shipment/) / [cac:Delivery](https://test-docs.peppol.eu/logistics/qa/syntax/AdvancedDespatchAdvice/cac-Shipment/cac-Delivery/) / [cac:EstimatedDeliveryPeriod](https://test-docs.peppol.eu/logistics/qa/syntax/AdvancedDespatchAdvice/cac-Shipment/cac-Delivery/cac-EstimatedDeliveryPeriod/) / [cbc:EndTime](https://test-docs.peppol.eu/logistics/qa/syntax/AdvancedDespatchAdvice/cac-Shipment/cac-Delivery/cac-EstimatedDeliveryPeriod/cbc-EndTime/)
[/ ](https://test-docs.peppol.eu/logistics/qa/rules/PEPPOL-T120-R013/syntax/Waybill/cac-Shipment/cac-Delivery/cac-EstimatedDeliveryPeriod/cbc-StartTime/)[ubl:Waybill](https://test-docs.peppol.eu/logistics/qa/syntax/Waybill/) / [cac:Shipment](https://test-docs.peppol.eu/logistics/qa/syntax/Waybill/cac-Shipment/) / [cac:Delivery](https://test-docs.peppol.eu/logistics/qa/syntax/Waybill/cac-Shipment/cac-Delivery/) / [cac:EstimatedDeliveryPeriod](https://test-docs.peppol.eu/logistics/qa/syntax/Waybill/cac-Shipment/cac-Delivery/cac-EstimatedDeliveryPeriod/) / [cbc:StartTime](https://test-docs.peppol.eu/logistics/qa/syntax/Waybill/cac-Shipment/cac-Delivery/cac-EstimatedDeliveryPeriod/cbc-StartTime/)
[/ ](https://test-docs.peppol.eu/logistics/qa/rules/PEPPOL-T120-R013/syntax/Waybill/cac-Shipment/cac-Delivery/cac-EstimatedDeliveryPeriod/cbc-EndTime/)[ubl:Waybill](https://test-docs.peppol.eu/logistics/qa/syntax/Waybill/) / [cac:Shipment](https://test-docs.peppol.eu/logistics/qa/syntax/Waybill/cac-Shipment/) / [cac:Delivery](https://test-docs.peppol.eu/logistics/qa/syntax/Waybill/cac-Shipment/cac-Delivery/) / [cac:EstimatedDeliveryPeriod](https://test-docs.peppol.eu/logistics/qa/syntax/Waybill/cac-Shipment/cac-Delivery/cac-EstimatedDeliveryPeriod/) / [cbc:EndTime](https://test-docs.peppol.eu/logistics/qa/syntax/Waybill/cac-Shipment/cac-Delivery/cac-EstimatedDeliveryPeriod/cbc-EndTime/)
[/ ](https://test-docs.peppol.eu/logistics/qa/rules/PEPPOL-T120-R013/syntax/Waybill/cac-Shipment/cac-Delivery/cac-Despatch/cac-EstimatedDespatchPeriod/cbc-StartTime/)[ubl:Waybill](https://test-docs.peppol.eu/logistics/qa/syntax/Waybill/) / [cac:Shipment](https://test-docs.peppol.eu/logistics/qa/syntax/Waybill/cac-Shipment/) / [cac:Delivery](https://test-docs.peppol.eu/logistics/qa/syntax/Waybill/cac-Shipment/cac-Delivery/) / [cac:Despatch](https://test-docs.peppol.eu/logistics/qa/syntax/Waybill/cac-Shipment/cac-Delivery/cac-Despatch/) / [cac:EstimatedDespatchPeriod](https://test-docs.peppol.eu/logistics/qa/syntax/Waybill/cac-Shipment/cac-Delivery/cac-Despatch/cac-EstimatedDespatchPeriod/) / [cbc:StartTime](https://test-docs.peppol.eu/logistics/qa/syntax/Waybill/cac-Shipment/cac-Delivery/cac-Despatch/cac-EstimatedDespatchPeriod/cbc-StartTime/)
[/ ](https://test-docs.peppol.eu/logistics/qa/rules/PEPPOL-T120-R013/syntax/Waybill/cac-Shipment/cac-Delivery/cac-Despatch/cac-EstimatedDespatchPeriod/cbc-EndTime/)[ubl:Waybill](https://test-docs.peppol.eu/logistics/qa/syntax/Waybill/) / [cac:Shipment](https://test-docs.peppol.eu/logistics/qa/syntax/Waybill/cac-Shipment/) / [cac:Delivery](https://test-docs.peppol.eu/logistics/qa/syntax/Waybill/cac-Shipment/cac-Delivery/) / [cac:Despatch](https://test-docs.peppol.eu/logistics/qa/syntax/Waybill/cac-Shipment/cac-Delivery/cac-Despatch/) / [cac:EstimatedDespatchPeriod](https://test-docs.peppol.eu/logistics/qa/syntax/Waybill/cac-Shipment/cac-Delivery/cac-Despatch/cac-EstimatedDespatchPeriod/) / [cbc:EndTime](https://test-docs.peppol.eu/logistics/qa/syntax/Waybill/cac-Shipment/cac-Delivery/cac-Despatch/cac-EstimatedDespatchPeriod/cbc-EndTime/)

**Comment by agrindst** [comment]
Closed, completed
