### ISSUE TITLE
Update engine types

### ISSUE THREAD

**Issue by areberg** [OpenPEPPOL/logistics-bis#179]
Engine types needs to be updated with: EV and Fuel Cell

Comment 11 Public review

**Comment by JorgenErlandsson** [comment]
Added "EV", "Hybrid" and "FuelCell" as allowed values in the description of the element Description under Shipment/Consignment/OriginalDespatchTransportationService/TransportEquipment/MeasurementDimension

**Comment by PeterLBorresen** [comment]
Verified!
