### ISSUE TITLE
Add attributes to cbc:TransportEquipmentTypeCode

### ISSUE THREAD

**Issue by areberg** [OpenPEPPOL/logistics-bis#181]
Add attributes like ListsID ListVersionID and name to cac:Shipment/cac:Consignment/cac:OriginalDespatchTransportationService/cac:TransportEquipment/cbc:TransportEquipmentTypeCode.

Comment 13 Public review

**Comment by JorgenErlandsson** [comment]
Message structure is now changed.

**Comment by PeterLBorresen** [comment]
Name is not added

**Comment by JorgenErlandsson** [comment]
The following attributes are added:
1. @listID                         Identity of the list.
2. @listAgencyID             Identity of the issuer of the list.
3. @listVersionID             Identity of the Version of the list.

An example:
<cbc:TransportEquipmentTypeCode listID="FuelGroup" listAgencyID="Trafikverket" listVersionID="2023:1"> HVO </cbc:TransportEquipmentTypeCode>
