### ISSUE TITLE
Update examples for cac:MeasurementDimension

### ISSUE THREAD

**Issue by areberg** [OpenPEPPOL/logistics-bis#182]
Update to the following: cbc:Measure=115.6 @unitCode=LTR. cac:Shipment/cac:Consignment/cac:OriginalDespatchTransportationService/cac:TransportEquipment/cac:MeasurementDimension. Also align examples to ISO-standard.

Comment 14 Public review

**Comment by PeterLBorresen** [comment]
Verified!
