### ISSUE TITLE
Add name attribute in cbc:ItemClassificationCode

### ISSUE THREAD

**Issue by areberg** [OpenPEPPOL/logistics-bis#183]
When listid="ZZZ" is used, the sender needs to provide name attribute so the receiver can understand what they are receiving. Add a business rule to validate that a name is populated whenever the listid="ZZZ".
Also align examples to ISO-standard.

Comment 15 Public review

**Comment by JorgenErlandsson** [comment]
Business rule R040 added to ADA, and also a unit test.

Snippet-files verified to be ok. No changes required.

Eight use-case example files are updated to show correct item numbers and versions.

**Comment by PeterLBorresen** [comment]
Verified!
