### ISSUE TITLE
Update example files and BIS

### ISSUE THREAD

**Issue by areberg** [OpenPEPPOL/logistics-bis#184]
Rename the example files so that they have a use case assigned to them. Also align examples to ISO-standard.

Comment 16 Public review

**Comment by JorgenErlandsson** [comment]
All example files are now linked with a use-case, ADA and RA. Two example files (old ones that were no longer relevant) are removed.

**Comment by PeterLBorresen** [comment]
Where are the samples for usecase 9-12 ?
