### ISSUE TITLE
Change Environmental Product Code (EPD) in example file and BIS

### ISSUE THREAD

**Issue by areberg** [OpenPEPPOL/logistics-bis#185]
Change according to tab 17_Correct_code.
The code and name for GWP GHG A1-3 vA2 EPD line value
AND
GWP-GHG_A1-3_vA2 is wrong in table 9 & 10. See tab 17 for details

Comment 17 Public review

**Comment by JorgenErlandsson** [comment]
BIS corrected.

**Comment by PeterLBorresen** [comment]
Verified!
