### ISSUE TITLE
Change description of cac:Shipment/cac:Delivery/cac:TransportHandlingUnit/cac:Status

### ISSUE THREAD

**Issue by areberg** [OpenPEPPOL/logistics-bis#187]
Since the cardinality is 1..1 (correct), this field cannot be omitted. Hence we need to change the description and remove "If omitted […] related to it".

Comment 24 Public review

**Comment by JorgenErlandsson** [comment]
Message structure is now changed.

**Comment by PeterLBorresen** [comment]
There is still an "if" in the description.

**Comment by JorgenErlandsson** [comment]
The description for cac:Status is changed to the description used in UBL 2.1.
