### ISSUE TITLE
Change description in cac:ReceiptLine/cac:DespatchLineReference/cbc:ID

### ISSUE THREAD

**Issue by areberg** [OpenPEPPOL/logistics-bis#188]
The cardinality is 1..1 (both cbc:ID and cac:DespatchLineReference), but there could be situations where this is not possible to comply with. Insert in the description the possibility to use "NA - dummy value" for specific situations of oversupply.

Comment 26 Public review.

**Comment by JorgenErlandsson** [comment]
Message structure is now changed.

**Comment by PeterLBorresen** [comment]
Verified!
