### ISSUE TITLE
Insert new element cbc:CategoryName in cac:HazardousItem

### ISSUE THREAD

**Issue by areberg** [OpenPEPPOL/logistics-bis#191]
Insert the field cbc:CategoryName (Hazardous substance category) with cardinality 0..1.

Comment 30 Public review.

**Comment by JorgenErlandsson** [comment]
Message structure is now changed.

**Comment by JorgenErlandsson** [comment]
Did not mean to close it - pushed the wrong button....

**Comment by PeterLBorresen** [comment]
Verified!
