### ISSUE TITLE
Add elements from eFTI-model to Hazardous Item

### ISSUE THREAD

**Issue by areberg** [OpenPEPPOL/logistics-bis#199]
Add following elements to cac:HazardousItem:
- cbc:Information (Information in eFTI-model)
- cac:HazardousGoodsTransit/cbc:PackingCriteriaCode (PackagingDangerLevelCode in eFTI-model)
- cbc:HazardClassID (HazardousClassificationID in eFTI-model)
- cbc:TunnelRestrictionCode (TunnelRestrictionCode in eFTI-model)
- cbc:HazardousCategoryCode (HazardousCategoryCode in eFTI-model)
- cbc:EmergencyTemperature (EmergencyTemperatureMeasure in eFTI-model)

**Comment by JorgenErlandsson** [comment]
Parts of this request was not possible to do since ADA is based on UBL 2.1. The last request (EmergencyTemperature) will be different than the request for the same reason.
Now the HazardousItem group looks like this:

<cac:HazardousItem>
       <cbc:ID>123</cbc:ID>
       <cbc:UNDGCode>ADR</cbc:UNDGCode>
       <cbc:TechnicalName>Corrosive liquid, n.o.s., 8, UN 1760, II (contains
 	          Octanoyl chloride)</cbc:TechnicalName>
	<cbc:CategoryName>Acute toxicity</cbc:CategoryName>		 
        <cbc:HazardousCategoryCode>123</cbc:HazardousCategoryCode>
	<cbc:HazardClassID>2.3</cbc:HazardClassID>
	<cbc:NetWeightMeasure unitCode="KGM">12345</cbc:NetWeightMeasure>
	<cbc:NetVolumeMeasure unitCode="MTQ">12.3</cbc:NetVolumeMeasure>
	<cac:HazardousGoodsTransit>
		<cbc:PackingCriteriaCode>123</cbc:PackingCriteriaCode>
	</cac:HazardousGoodsTransit>
	<cac:EmergencyTemperature>
		<cbc:AttributeID>ABC</cbc:AttributeID>
		<cbc:Measure unitCode="CEL">78</cbc:Measure>
	</cac:EmergencyTemperature>
</cac:HazardousItem>

**Comment by JorgenErlandsson** [comment]
Element AdditionalInformation also added (instead of the requested Information).
