### ISSUE TITLE
Correct TransportExecutionPlan source-file

### ISSUE THREAD

**Issue by areberg** [OpenPEPPOL/logistics-bis#203]
Correct following errors:
Replace cac:Location with cac:DeliveryLocation in cac:DeliveryTerms.
Add attribute currencyID to cac:FreightAllowanceCharge/cbc:Amount.

Update all Use-case example files accordingly.

**Comment by PeterLBorresen** [comment]
Corrected in TransportExecutionPlan_Example_Full. Did not find the error in the usecase samples.

**Comment by areberg** [comment]
I can fix the use-case examples.
