### ISSUE TITLE
Correct TransportationStatus source-file

### ISSUE THREAD

**Issue by areberg** [OpenPEPPOL/logistics-bis#205]
Attribute schemeID is not allowed in cac:Consignment/cac:TransportEvent/cac:CurrentStatus/cbc:ConditionCode.
Attribute schemeID is not allowed in cac:Consignment/cac:TransportHandlingUnit/cac:Status/cbc:ConditionCode.
Attribute schemeID is not allowed in cac:TransportEvent/cac:CurrentStatus/cbc:ConditionCode.
cac:TransportEvent shall be placed before cac:DocumentReference in main structure.

Update all Use-case example files accordingly.

**Comment by PeterLBorresen** [comment]
Done
