### ISSUE TITLE
Remove cbc:EndpointID from all parties but two

### ISSUE THREAD

**Issue by RikardLarsson-BEAst** [OpenPEPPOL/logistics-bis#24]
In Peppol there are usually two parties that has endpointid and the id is used to also populate the envelope (SBDH). We should try to use the same principle.

**Comment by DidrikN** [comment]
@PeterLBorresen: Can you please have a look at this? 

As seen [here](https://test-docs.peppol.eu/logistics/transport-execution/), the count for EndpointID is currently 10.

**Comment by PeterLBorresen** [comment]
Hi Richard

 

When it comes to information sharing, Peppol Logistics is closer to the Peppol pre-award than the Peppol post-award. In Peppol Logistic we have a sender and a receiver of the document, but there can be other parties who need the information and want to be informed about updates etc. When I presented the Scenario 3, you saw this in the sequence diagram, but off cause this can be done in at least three ways:

 

1.	The Sender of the document sends it to all relevant parties
2.	The integrator (organizer of the transport) sends this to all relevant parties
3.	The distribution of information to the parties involved in the logistics happens with other means than Peppol. The Peppol message is only passed between the sender and the reciver of the document.

 

I think that the project group should discuss this, but until then I will recommend that the parties has the necessary informations to share the relevant information.

 

Best regards

 

Peter

 

From: RikardLarsson-BEAst ***@***.***> 
Sent: Tuesday, February 21, 2023 4:49 PM
To: OpenPEPPOL/logistics-bis ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [OpenPEPPOL/logistics-bis] Remove cbc:EndpointID from all parties but two (Issue #24)

 

In Peppol there are usually two parties that has endpointid and the id is used to also populate the envelope (SBDH). We should try to use the same principle.

**Comment by DidrikN** [comment]
@areberg: This is probably a decision point that we need to add the agenda for next PG-meeting.

**Comment by agrindst** [comment]
New issue created on this, and closing this one. 

New issue: 
EndpointID on only two parties #36
[https://github.com/OpenPEPPOL/logistics-bis/issues/36](url)
