### ISSUE TITLE
Both Country identification code and country name

### ISSUE THREAD

**Issue by DidrikN** [OpenPEPPOL/logistics-bis#25]
There are currently both country IdentificationCode and country name on several elements in Transport Execution Plan Request.
In advanced despatch advice we only had "IdentificationCode", so I'm guessing this is sufficient also for Transport Execution Plan Request?

I have found these instances of this:
cac:Consignment / cac:PreCarriageShipmentStage / cac:CarrierParty / cac:PostalAddress / cac:Country
cac:Consignment / cac:ConsignorParty / cac:PostalAddress / cac:Country
cac:Consignment / cac:FreightForwarderParty / cac:PostalAddress / cac:Country

My suggestion is to remove "Name" from these Country-elements.

**Comment by DidrikN** [comment]
@PeterLBorresen: Any comments on this? Did you make it like tis on purpose or can we remove the "Name"-elements from Country?

**Comment by PeterLBorresen** [comment]
I will allign this to the other Peppol specifications

**Comment by DidrikN** [comment]
@PeterLBorresen: Please remove "Country name" from all instances as Country identification code is sufficient, as agreed in the WG-meeting Monday February 27th.

**Comment by PeterLBorresen** [comment]
Done

**Comment by agrindst** [comment]
Name is removed in: 
cac:Consignment / cac:PreCarriageShipmentStage / cac:CarrierParty / cac:PostalAddress / cac:Country
cac:Consignment / cac:ConsignorParty / cac:PostalAddress / cac:Country

Considering: 
cac:Consignment / cac:FreightForwarderParty / cac:PostalAddress / cac:Country
[Issue 48](https://github.com/OpenPEPPOL/logistics-bis/issues/48)
reffering to issue 48 , FreightForwarderParty is removed.
