### ISSUE TITLE
VersionID for Transport Execution Plan Request

### ISSUE THREAD

**Issue by DidrikN** [OpenPEPPOL/logistics-bis#26]
VersionID is currently included in the Transport Execution Plan Request - do we want this?

We have excluded this for both Advanced Despatch Advice and Despatch Advice Response.

**Comment by DidrikN** [comment]
For Advanced Despatch Advice and Despatch Advice Response, we decided that we instead would use IssueDate and IssueTime.
We already have these two elements in Transport Execution Plan Request, therefore my **suggestion** is to remove VersionID from Transport Execution Plan Request.

Background:
![image](https://user-images.githubusercontent.com/33622175/220557297-5d00e814-5b53-4e0a-8764-2181b486e08c.png)

**Comment by DidrikN** [comment]
For Advanced Despatch Advice and Despatch Advice Response, we decided that we instead would use IssueDate and IssueTime.
We already have these two elements in Transport Execution Plan Request, therefore my **suggestion** is to remove VersionID from Transport Execution Plan Request.

Background:
![image](https://user-images.githubusercontent.com/33622175/220557297-5d00e814-5b53-4e0a-8764-2181b486e08c.png)

**Comment by DidrikN** [comment]
@PeterLBorresen: Please remove **versionID** from **Tranport Exectuion Plan Request** as agreed in the WG on Monday February 27h.

**Comment by PeterLBorresen** [comment]
Done. Shouldn't issuetime then be mandatory?

**Comment by agrindst** [comment]
Validated that versionID is removed, 

Reguarding IssueTime please see issue #34
