### ISSUE TITLE
IdentificationID - Rename to ID?

### ISSUE THREAD

**Issue by DidrikN** [OpenPEPPOL/logistics-bis#27]
Currently, there are several elements named "IdentificationID" in the Transport Execution Plan Request.
Are these named this way by purpose - or should they be named differently e.g "ID"?

**Comment by DidrikN** [comment]
@PeterLBorresen Any comments on this?

**Comment by PeterLBorresen** [comment]
I have the comment that ihis is the UBL name for is, see http://www.datypic.com/sc/ubl23/t-cac_TransportEventType.html

**Comment by PeterLBorresen** [comment]
So I recommend not to change the name.

**Comment by DidrikN** [comment]
Thanks for clarifying @PeterLBorresen. Closing this with no action required. As the name is "IdentificationID" in UBL 2.3, we keep it as is.
