### ISSUE TITLE
Compliancy between Despatch Advice (PoAC) and Advanced Despatch Advice (Logistics)

### ISSUE THREAD

**Issue by DidrikN** [OpenPEPPOL/logistics-bis#28]
Based on discussions in kick-off meeting it is obvious that Despatch Advice is in use, by e.g. Italy.

We need to clarify the compliancy between Despatch Advice (PoAC) and Advanced Despatch Advice (Logistics).
What do we do with elements that currently is non-compliant - do we submit a request for change (RFC) to PoAC for these elements, or will we potentially adjust the next version of Advanced Despatch Advice?

**Comment by DidrikN** [comment]
The non-compliant elements that are found for now includes the following two elements:

**1)**
The party structure that we have chosen for Advanced Despatch Advice differs from the party structure in Despatch Advice.
We have in the process with the Advanced Despatch Advice concluded that this is an improvement, and we want to submit an RFC to align the structure in Despatch Advice (and also add more information on for example sender party in invoice response).

**2)**
We have removed "Shipment" from "DespatchLine"/Line-level as we now have this on different level. We also want this for Despatch Advice (PoAC).

**Comment by agrindst** [comment]
actions: 

- [ ] sendt an RFC to PoAC about information of existing use of the Despatch Advice, awaiting an answer.

**Comment by areberg** [comment]
We will address the need for coordination between PoAC and Logistics in the PoAC-Webinar in september.
