### ISSUE TITLE
Wrong title/name on PartyLegalEntity

### ISSUE THREAD

**Issue by DidrikN** [OpenPEPPOL/logistics-bis#29]
**PartyLegalEntity** is currently titled with "Party name" for both Advanced Despatch Advice 1.1 and Despatch Advice Response 1.1.
 
Please adjust this to be titled "Party legal entity" in next version.

**Comment by JorgenErlandsson** [comment]
Yes, this should be corrected.

**Comment by agrindst** [comment]
@JorgenErlandsson please complete this issue

**Comment by JorgenErlandsson** [comment]
This issue is now fixed and should be closed.
