### ISSUE TITLE
Line in AddressLine should be mandatory for all PostalAddresses/Addresses on parties

### ISSUE THREAD

**Issue by PeterLBorresen** [OpenPEPPOL/logistics-bis#30]
AddressLine it self is optional, so Line should be mandatory

**Comment by DidrikN** [comment]
Just to add some more info, this is for all PostalAddress/Addesses on parties.
In cases such as this:
https://test-docs.peppol.eu/logistics/transport-execution/syntax/AdvancedDespatchAdvice/cac-OriginatorCustomerParty/cac-Party/cac-PostalAddress/

**Comment by DidrikN** [comment]
This needs to be corrected for:
- [ ] Transport Execution Plan Request 1.0
- [ ] Advanced Despatch Advice 1.2

**Comment by DidrikN** [comment]
@PeterLBorresen: Please make **"Line"** mandatory for all the instances of **"AddressLine"** in **Transport Execution Plan Request**, as agreed in the WG-meeting on Monday February 27th.

**Comment by PeterLBorresen** [comment]
Done

**Comment by agrindst** [comment]
Validated that "Line" is mandatory for all instances of "AddressLine"
