### ISSUE TITLE
Consider cardinallity in delivery

### ISSUE THREAD

**Issue by PeterLBorresen** [OpenPEPPOL/logistics-bis#31]
In delivery both delivery location and despatch are optional. Is this ok? Should we have a description saying that in case the delvery location is not described then it is considered to be the address of the delivery party?

**Comment by JorgenErlandsson** [comment]
This is close to the same as issue #62. We cannot have anything in the Delivery group mandatory since we then would not support all of our use-cases.
However, the improvement of the description of DeliveryLocation, I think is a good idea.

**Comment by agrindst** [comment]
Decided Action: 
Do not change cardinality. Add a better description 

@JorgenErlandsson

**Comment by JorgenErlandsson** [comment]
The description is now improved and this issue should be closed.
