### ISSUE TITLE
Line in AddressLine should be mandatory for all PostalAddresses/Addresses on parties

### ISSUE THREAD

**Issue by DidrikN** [OpenPEPPOL/logistics-bis#32]
AddressLine it self is set to optional, so Line should be mandatory.

There is a total of 8 AddressLine elements in Advanced Despatch Advice, with 8 underlying "Line" elements.
7 of these "Line" are set to "optional" - needs to be adjusted to mandatory.

**Comment by JorgenErlandsson** [comment]
Technically this is correct - we should set the Line to mandatory. But in the T16 DespatchAdvice it is optional and we would need to create a RFC to change it there too if we decide to change here. Do we want to spend time on that now?

**Comment by JorgenErlandsson** [comment]
This issue is now fixed and can be closed.
