### ISSUE TITLE
Make IssueTime mandatory

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#34]
Make IssueTime mandatory. 

[https://test-docs.peppol.eu/logistics/transport-execution/syntax/TransportExecutionPlanRequest/cbc-IssueTime/](url)
[https://test-docs.peppol.eu/logistics/transport-execution/syntax/TransportExecutionPlan/cbc-IssueTime/](url)

Decision made by workgroup.

**Comment by agrindst** [comment]
@PeterLBorresen please comlplete this

**Comment by PeterLBorresen** [comment]
Done

**Comment by agrindst** [comment]
Validated that issueTime is mandatory in Transport Execution plan Request. 

Still need to: 
- [ ] make issueTime mandatory in Transport Execution plan 

@PeterLBorresen

**Comment by PeterLBorresen** [comment]
Done, checked
