### ISSUE TITLE
Make IssueTime mandatory 

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#35]
Make IssueTime mandatory.

- [x] Advanced despatch advice 
- [x] Despatched advice with response
- [x] Weight statement 

Advanced despatched advice: 
[https://test-docs.peppol.eu/logistics/test-cs/syntax/AdvancedDespatchAdvice/cbc-IssueTime/](url)

Despatched advice with response: 
[https://test-docs.peppol.eu/logistics/test-cs/syntax/DespatchAdviceResponse/cbc-IssueTime/](url)

Weight statement: 
[https://test-docs.peppol.eu/logistics/test-cs/syntax/WeightStatement/cbc-IssueTime/](url)

Decision made by workgroup.

**Comment by JorgenErlandsson** [comment]
Agree that we should change cardinality to mandatory.

**Comment by agrindst** [comment]
Please complete this issue, make IssueTime mandatory in Weight Statement

**Comment by JorgenErlandsson** [comment]
This issue is now solved and can be closed.
