### ISSUE TITLE
EndpointID on only two parties

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#36]
When it comes to information sharing, Logistics might be a bit closer to Pre-Awards (PrAC) when it comes to who needs/wants the information. In Logistics we have a sender and a receiver of the document, but there can be other parties who need the information and want to be informed about updates etc. This can be done in several ways:​

1. The Sender of the document sends it to all relevant parties​
2. The integrator (organizer of the transport) sends this to all relevant parties​
3. The distribution of information to the parties involved in the logistics happens with other means than Peppol. The Peppol message is only passed between the sender and the receiver of the document.

How do we want to solve this in the Transport Execution Plan Request? Do we want to follow a principle with only two EndpointIDs, or do we want to solve this in a different way with more than two EndpointIDs?​​

**Comment by agrindst** [comment]
Will be discussed in project group meeting. Suggested decision:​
Keep only two EndpointIDs  (Sender / Receiver of document).

**Comment by agrindst** [comment]
As decided by the project group we will keep only two EndpointIDs 


Action needed: 
- [ ] remove additional EndpointIDs, and keep only two

**Comment by PeterLBorresen** [comment]
I think we need to solve the different Party templates. In Advanced Despatch Advice we have two.

**Comment by agrindst** [comment]
As agreed on in WG, Peter will check and look into rules of different party templates

**Comment by agrindst** [comment]
One possible solution is to have EndpointID on two parties mandatory, however open to the possibility to have EndpointIDs on others as well (optional).

**Comment by agrindst** [comment]
Actions: 

- [ ] Have EndpointID on only sender and receiver

**Comment by areberg** [comment]
Does this mean the SenderParty and the ReceiverParty or the party actually sending and receiving the transaction, the TransportUserParty and the TransportServiceProviderParty? The last two are mandatory in UBL.

**Comment by PeterLBorresen** [comment]
Done
