### ISSUE TITLE
OutstandingReason rule

### ISSUE THREAD

**Issue by PeterLBorresen** [OpenPEPPOL/logistics-bis#40]
OutstandingReason should be specified when outstanding quantity is present different from zero. Suggest a new business rule (warning) to check for this.

**Comment by DidrikN** [comment]
I'm guessing this is related to [Advanced Despatch Advice.](https://test-docs.peppol.eu/logistics/transport-execution/syntax/AdvancedDespatchAdvice/cac-DespatchLine/cbc-OutstandingReason/)

I have added this to the backlog on this message format, and we will visit this issue later.

**Comment by JorgenErlandsson** [comment]
I do not agree. The reason is most likely not known by persons packing the goods. Informing about the reason is something for the OrderResponse transaction, not the DespatchAdvice. I suggest to leave it as it is.

**Comment by agrindst** [comment]
Discuss in WG

**Comment by agrindst** [comment]
As discussed in WG, Peter please create this rule

**Comment by agrindst** [comment]
Assigned to Jorgen

**Comment by JorgenErlandsson** [comment]
Found that this rule already exists - R007. Issue can be closed.
