### ISSUE TITLE
PostAddress / Address aligned across all formats

### ISSUE THREAD

**Issue by DidrikN** [OpenPEPPOL/logistics-bis#43]
PostAddress / Address needs to be aligned across all formats, so that we have the same content in all "Address"-groups.

Tasks:
- [ ] Agree on correct content of group

Implement:
- [ ] Transport Execution Plan Request 1.0

Verify alignment (when not aligned - create issue for the different formats):
- [ ] Advanced Despatch Advice 1.2
- [ ] Despatch Advice Response 1.2
- [ ] Weight Statement 1.2

**Comment by agrindst** [comment]
Comparison PostalAddress across Advance Despatch Advice, Despatch Advice Response, Transport Execution Plan Request, Transport Execution Plan, Waybill, Receipt Advice:

[Peppol Logistics l Aligning Postal adress.xlsx](https://github.com/OpenPEPPOL/logistics-bis/files/11342864/Peppol.Logistics.l.Aligning.Postal.adress.xlsx)

**Comment by agrindst** [comment]
continue in #146
