### ISSUE TITLE
PayeeParty on TransportExecutionPlanRequest

### ISSUE THREAD

**Issue by DidrikN** [OpenPEPPOL/logistics-bis#44]
The parties currently represented directly under [ubl:TransportExecutionPlanRequest](https://test-docs.peppol.eu/logistics/transport-execution/syntax/TransportExecutionPlanRequest/) is:
- cac:SenderParty
- cac:ReceiverParty 
- cac:TransportUserParty
- cac:TransportServiceProviderParty

The general rule is that TransportUserParty is the same party as the TransportPayerParty, however, there are usecases where these parties are different, and where we therefore need them both (as discussed in WG-meeting February 27th).

Thefore, please:
- [ ] Add TransportPayerParty to TransportExecutionPlanRequest.

**Comment by DidrikN** [comment]
@PeterLBorresen: Please add TransportPayerParty on [ubl:TransportExecutionPlanRequest](https://test-docs.peppol.eu/logistics/transport-execution/syntax/TransportExecutionPlanRequest/).

**Comment by PeterLBorresen** [comment]
Ubl does not have a transport payer party. I can facillitate it to be added to UBL 2.4 if we are sure there is a need for this. Please see my comment from the mapping against the Bring Edifact super set.

**Comment by PeterLBorresen** [comment]
Added

**Comment by agrindst** [comment]
Validated that payee party is added
