### ISSUE TITLE
Insurance-elements for Consignment in TransportExecutionPlanRequest

### ISSUE THREAD

**Issue by DidrikN** [OpenPEPPOL/logistics-bis#45]
The usecase for "TotalInvoiceAmount" on Consignment in TransportExecutionPlanRequest is purely related to insurance.

We have therefore agreed on removing "TotalInvoiceAmount" and replace this with a more suitable element.

Tasks:
- [ ] Remove TotalInvoiceAmount
- [ ] Add InsuranceInvoiceAmount

**Comment by DidrikN** [comment]
@PeterLBorresen Please complete this change.

**Comment by PeterLBorresen** [comment]
Done

**Comment by agrindst** [comment]
Validate InsuranceValueAmount is present in Transport Execution plan Request
