### ISSUE TITLE
InsuranceParty for TransportExecutionPlanRequest

### ISSUE THREAD

**Issue by DidrikN** [OpenPEPPOL/logistics-bis#46]
As part of the discussions on [TotalInvoiceAmount/InsuranceValueAmount](https://github.com/OpenPEPPOL/logistics-bis/issues/45), there was a suggestion to also include information about the [InsuranceParty](http://www.datypic.com/sc/ubl23/e-cac_InsuranceParty.html). Suggestion was mentoned by transporter Bring, and this might be useful for more transporters.

Do we want this?

Tasks:
- [ ] Discuss this possible addition in WG-meeting
- [ ] Complete / disregard the change

**Comment by DidrikN** [comment]
We have sent a request for more information from Bring (@Atle).

**Comment by agrindst** [comment]
Update, received information from Bring (Atle): 

The carrier has no relation to what transport insurance the individual Property Owner has, this is between the individual company and their insurance company.
It is the goods owner who must insure their goods as it is the goods owner who knows the value of the goods. 

In addition, the carrier is liable for compensation for damaged and lost goods up to a certain amount per kilogram of goods. 

There are therefore two different types of insurance: 

- Goods liability insurance: This is insurance that the carrier buys to cover damage that occurs to the customer's goods during loading, unloading, and transport ref. Road Freight Act. 
- The transport insurance (this is an insurance the goods owner must sign) covers damage to own goods, regardless of who transports them.

As a principle, nothing is signed in a transport order, but this may contain information about the goods owner's insurance policies for the goods.

**Comment by agrindst** [comment]
As decided, we will not include InsuranceParty in this first version sent out for internal review
