### ISSUE TITLE
Contact info missing on ConsignorParty and ConsigneeParty

### ISSUE THREAD

**Issue by DidrikN** [OpenPEPPOL/logistics-bis#47]
Contact information is missing on both ConsignorParty and ConsigneeParty.
As discussed in the WG-meeting on Monday February 27th, please add this information.

Task:
- [ ] Add contact-group to **Consignor**Party
- [ ] Add contact-group to **Consignee**Party

**Comment by DidrikN** [comment]
@PeterLBorresen: Please complete this change.

**Comment by PeterLBorresen** [comment]
Done

**Comment by agrindst** [comment]
ConsignorParty and ConsigneeParty is added
