### ISSUE TITLE
Sigature for WayBill and/or TransportationStatus

### ISSUE THREAD

**Issue by DidrikN** [OpenPEPPOL/logistics-bis#49]
Question raised by @PeterLBorresen.

**Where**
On document level for all documents in the execution phase of logistics (Waybill, transportationStatus).

**Why**
In logistics many documents needs to be signed at the handover of the logistics. This can replace the manual processes here, or can document usage of electronic signing means.

**Comment**
Can be considered to be used in despatch advice as well.

**Comment by DidrikN** [comment]
We detirmed in work group meeting March 6th, that this is not applicable for TransportExecutionPlanRequest / TransportExecutionPlan.

Will revisit this when we get to Waybill and/or Transportation Status.

**Comment by agrindst** [comment]
We have initiated developing Waybill, and signature has been addressed as something we need to discuss further. 

From the discussion in WG: 
- Signature is a Key thing 
need to discuss: 

- [ ] do we need mandatory signature?
- [ ] do we need more than one signature?

**Comment by agrindst** [comment]
From the Project group meeting at 12.04.23:

The project group has discussed and found out that there are differences between proceeding Waybill inn different countries. 
The project group agreed that signature shall be included in waybill, and that is should be optional and not mandatory.

**Comment by agrindst** [comment]
Comment to mail from Jorgen Hensgens: this is dependent on the way of transporting (air, road etc.) 

Suggestion: add a business rule that describes this

**Comment by PeterLBorresen** [comment]
Signature is 0..n as agreed.

**Comment by PeterLBorresen** [comment]
In Transportation status we agreed to have the signature on event.

**Comment by agrindst** [comment]
Signature is added to Transport Event, however it is still present under the overall Transportation Status. 

https://test-docs.peppol.eu/logistics/qa/syntax/TransportationStatus/cac-Signature/

actions: 

- [ ] remove signature

**Comment by agrindst** [comment]
We will include Signature on both places for this first internal review.
