### ISSUE TITLE
DocumentID TransportExecutionPlan = "Booking identifier"

### ISSUE THREAD

**Issue by DidrikN** [OpenPEPPOL/logistics-bis#50]
Please better describe that the DocumentID in TransportExecutionPlan is the booking identifier.

**Comment by DidrikN** [comment]
@PeterLBorresen Please complete this.

**Comment by PeterLBorresen** [comment]
This needs to be explained in the BIS

**Comment by agrindst** [comment]
This issue has been fulfilled by Are
