### ISSUE TITLE
PaymentTerms under Consigment in TransportExecutionPlanRequest/TransportExecutionPlan

### ISSUE THREAD

**Issue by DidrikN** [OpenPEPPOL/logistics-bis#51]
Reported by @PeterLBorresen 

**What**
Payment Terms

**Where**
Consignment in TransportExecutionPlan/TransportExecutionPlanRequest

**Why**
Specifies how the transport is paid.

**Comment**
Can be considered to out of scope.

**Comment by DidrikN** [comment]
Concluded in WG-meeting that Payment terms under Consignment must be added.
@PeterLBorresen: Please complete this.

**Comment by agrindst** [comment]
Validated, payment terms is added
