### ISSUE TITLE
Descriptions for party identification

### ISSUE THREAD

**Issue by PeterLBorresen** [OpenPEPPOL/logistics-bis#53]
Party identifications has no name or descriptions in Despatch advice (or in Invoice). Maby we can improve this like

An identifier of the despatch supplier party as known for the delivery customer party

The idea is to say who owns this identifier and who is supposed to use it.

**Comment by JorgenErlandsson** [comment]
Tis is correct for the group PartyIdentification, but in the element ID inside the group it is described who's ID it is. I believe that is enough.

**Comment by agrindst** [comment]
After discussions we have decided to not make any changes regarding this issue.
