### ISSUE TITLE
Use of capital letters

### ISSUE THREAD

**Issue by PeterLBorresen** [OpenPEPPOL/logistics-bis#55]
There is some inconsistency in when to use capital letters. Is it Transport User Party, transport user party or Transport user party? What is the rule.

**Comment by agrindst** [comment]
Will bring this issue to WG meeting.

**Comment by PeterLBorresen** [comment]
The agreement is that the first letter should be capital, eg. Transport execution plan.

**Comment by agrindst** [comment]
As desided: 
Party name and other similar names should be written as sentence case. 

Actions 
- [ ] review all transactions and documentation
- [ ] inform everyonoe
