### ISSUE TITLE
New profile for update of transport executionplan

### ISSUE THREAD

**Issue by PeterLBorresen** [OpenPEPPOL/logistics-bis#56]
The situation of updating a transport execution plan is different from sending a new one. It should be considered if a new profile id could be helpfull for this. 

It is also important to consider the case of prebooking, that is when the carrier is told to come and pickup some goods at some time, but it is unspecific how much and maybe also where it is going to. This has to be in place before the booking is properly confirmed.

**Comment by areberg** [comment]
We have already described a scenario for the change of a transport execution plan using the document status code 5 (replace).

**Comment by agrindst** [comment]
To be discussed in WG meeting

**Comment by agrindst** [comment]
Decided in WG meeting that using the document status code 5 is sufficient
