### ISSUE TITLE
Consider removing Delivery contact

### ISSUE THREAD

**Issue by PeterLBorresen** [OpenPEPPOL/logistics-bis#59]
There exists allready a contact on delivery party. We need a rule or an explanation if we have both.

**Comment by DidrikN** [comment]
The information is currently in two place on cac-DeliveryCustomerParty: 
- https://test-docs.peppol.eu/logistics/syntax/AdvancedDespatchAdvice/cac-DeliveryCustomerParty/cac-Party/cac-Contact/
- https://test-docs.peppol.eu/logistics/syntax/AdvancedDespatchAdvice/cac-DeliveryCustomerParty/cac-DeliveryContact/

**Comment by JorgenErlandsson** [comment]
Since the DeliveryContact is included in the T16 DespatchAdvice I suggest to remove the other contact - the one we added in 1.1 in the Party group.
This issue is also reported by the project group during the evaluation period.

**Comment by JorgenErlandsson** [comment]
The DeliveryContact group is now removed. Issue can be closed.
