### ISSUE TITLE
Check use of existing Despatch Advice today (PoAC)

### ISSUE THREAD

**Issue by DidrikN** [OpenPEPPOL/logistics-bis#6]
We have changed structure in Advanced Despatch Advice compared to Despatch Advice, and we need to either defend these changes or make the new advanced format backwards compatible with existing despatch advice. 

In this, we want to check the use of Despatch Advice today, so that we know the impact of the change.
Check this with both Pietro (?) and Industrigruppen (???)

The changes:
Shipment under line.
LicensePlateID is on different element

**Comment by areberg** [comment]
Based on discussions in kick-off meeting it is obvious that Despatch Advice is used in Italy. We will anyhow have to clarify compliancy between Despatch Advice and Advanced Despatch Advice. This issue can be closed and we should make a new issue for this clarification.

**Comment by DidrikN** [comment]
Closing this issue as we have clarified that the Despatch Advice clearly is in use in Italy. We now have to investigate the compliancy between Despatch Advice (PoAC) and Advanced Despatch Advice (Logistics).

Follow up issue: https://github.com/OpenPEPPOL/logistics-bis/issues/28
