### ISSUE TITLE
Consider cardinallity of Delivery location/ ID

### ISSUE THREAD

**Issue by PeterLBorresen** [OpenPEPPOL/logistics-bis#61]
In case the delivery location is using an address, why do we then need to specify the delivery location id. Maybe we need a business rule for this?

**Comment by agrindst** [comment]
Peter is suggesting to change Delivery location to not mandatory. 

suggestion: 
make a business rule that about specifying address or Location ID

**Comment by JorgenErlandsson** [comment]
I agree that the ID must be changed to optional. Sometimes the DeliveryLocation is just some gps coordinates and we must allow that. 
Since the location can be more or less anything I do not see that we need any rule to check it.

Suggest to change cardinality to 0..1 only.

**Comment by agrindst** [comment]
Please complete this issue

Actions: 

- Change Cardinality to 0..1

**Comment by JorgenErlandsson** [comment]
This issue is now fixed and can be closed.
