### ISSUE TITLE
Consider cardinallity in Delivery

### ISSUE THREAD

**Issue by PeterLBorresen** [OpenPEPPOL/logistics-bis#62]
Delivery is a cornerstone in Despatch advice, but it is optional in shipment. In Delivery you dont have to specify anything at all. I would say that a deliverylocation and a Estimated OR and actual delivery date time should be mandatory,

**Comment by JorgenErlandsson** [comment]
Delivery indeed could be set to mandatory but that then would be different to the T16 DespatchAdvice and as I see it, it is not so important that we should spend time on a RFC to get it mandatory in T16 too.

Looking at our 11 use-cases there is nothing in the Delivery group that is included in all of them. If we want to make anything mandatory in Delivery we will have to remove some use-cases, different use-cases depending on what we make mandatory.

I suggest that we leave it as it is and close this issue.

**Comment by PeterLBorresen** [comment]
Again I dont think that conpiance with T16 is a an issue we should prioritize.

**Comment by agrindst** [comment]
Decided not to make any changes in this version. 

will be reviewed in later version
