### ISSUE TITLE
Use despatch location in stead of despatch address

### ISSUE THREAD

**Issue by PeterLBorresen** [OpenPEPPOL/logistics-bis#63]
Instead of using despatch address it should be considered to use despatch location instead. This will align it with delivery.

**Comment by JorgenErlandsson** [comment]
I agree that the DespatchLocation would be a better choise than the DespatchAddress, but since the Peppol DespatchAdvice (T16) use the DespatchAddress I do not believe this change is so important that we should do it. That would mean that we would need a RFC on T16 as well.

**Comment by PeterLBorresen** [comment]
I think there is a long list of things we allredy has corrected from T16. I believe this transaction should be replaced with T120 - This is the transaction CEN TC 440 is following.

**Comment by agrindst** [comment]
Decided not to change to Despatch logcation.
