### ISSUE TITLE
Consider cardinality of Certificate type code

### ISSUE THREAD

**Issue by PeterLBorresen** [OpenPEPPOL/logistics-bis#64]
In Despatch Advice Certificate, both certificate type code and certificate type are mandatory. A normal way would be to say that they both are optional, but apply a business rule saying that one of them has to be specified.

**Comment by JorgenErlandsson** [comment]
This is not possible to do since in UBL 2.2 both elements are mandatory. This will have to wait until we base the DespatchAdvice on a later UBL version.. Suggest to close this issue.

**Comment by PeterLBorresen** [comment]
Yes, but we are using UBL 2.3, where this has been corrected, see http://www.datypic.com/sc/ubl23/e-cac_Certificate.html

**Comment by agrindst** [comment]
In the PG meeting on 15 February, the WG suggested using UBL 2.3. 
There were no rejections of this proposal.

https://github.com/OpenPEPPOL/logistics-bis/issues/18

**Comment by agrindst** [comment]
Suggestion: 
for WP #1, 2, 3 and 4 using UBL 2.3

for WP #0: 
Weight statement: UBL 2.3

Despatched Advice: 
Keep 2.1 until the UBL 2.4 is published. Then update to UBL 2.4

**Comment by agrindst** [comment]
Decided to not make any changes

**Comment by agrindst** [comment]
Will be reviewed when UBL 2.4 is released
