### ISSUE TITLE
Consider to remove sender and receiver

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#68]
There has been a suggestion to remove the sender and receiver in the Transport Execution Plan Request, and Transport Execution plan. 

Background for the suggestion: Transport User is the one sending the message.  

Will be discussed in WG

**Comment by PeterLBorresen** [comment]
Well spotted! So we can removed sender and receiver party from Transport Execution Plan request?

 

/Peter

**Comment by PeterLBorresen** [comment]
Removed sender and receiver party to transport execution plan request.
