### ISSUE TITLE
Returnable Unit on Transport Equipment

### ISSUE THREAD

**Issue by PeterLBorresen** [OpenPEPPOL/logistics-bis#69]
Since Transport Hanling Unit and Package are representing the same thing (for instance a Pallet) it should be possible to represented in both abie or none of them if a Package or transport equipment is returnable. Suggestion: Add ReturnabillityIndicator to Item Equipment.

**Comment by agrindst** [comment]
As of now, ReturnabilityIndicator is located at package level.

decision: 
- [ ] should we move ReturnabilityIndicator to item level 
- [ ] should we have ReturnabilityIndicator at both package and item level

**Comment by agrindst** [comment]
Leave it as is
