### ISSUE TITLE
Add Version ID or an Indexing 

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#70]
The PG agreed that the Waybill will be updated by sending a new Waybill. 
The PG also specified that Waybill needs to include a version ID or an Indexing.

**Comment by agrindst** [comment]
@PeterLBorresen, can you please look into this

- [ ] verify possibility
- [ ] suggest possible solutions

**Comment by PeterLBorresen** [comment]
Added versionID to transport execution plan request + made Issue time optional.

**Comment by PeterLBorresen** [comment]
Due to agreement this has been removed again. Waiting for further instructions

**Comment by agrindst** [comment]
Closing this issue. will be reviewed when UBL 2.4 is released.
