### ISSUE TITLE
TransportServiceProviderParty 

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#73]
As agreed in WG, and as described in Excel-document Comments l Transport Execution plan Request:
[Comments l Transport Execution plan Request.xlsx](https://github.com/OpenPEPPOL/logistics-bis/files/11321469/Comments.l.Transport.Execution.plan.Request.xlsx)

Please complete the following actions, in TransportExecutionPlanRequest under TransportServiceProviderParty: 

- [x] remove EndpointID
- [x] change PartyIdentification to optional 
- [x] change schemeID in ID in PartyIdentification to optional
- [x] change PostalAdress to optional
- [x] change StreetName in PostalAdress to optional

**Comment by agrindst** [comment]
https://test-docs.peppol.eu/logistics/transport-execution/syntax/TransportExecutionPlanRequest/cac-TransportServiceProviderParty/

**Comment by PeterLBorresen** [comment]
done

**Comment by agrindst** [comment]
@PeterLBorresen please remove EndpointID

**Comment by PeterLBorresen** [comment]
Endpoint removed

**Comment by agrindst** [comment]
completed
