### ISSUE TITLE
Add atributes to MainTransportationService and AdditionalTransportationService

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#74]
As commented in: 
[Comments l Transport Execution plan Request.xlsx](https://github.com/OpenPEPPOL/logistics-bis/files/11321612/Comments.l.Transport.Execution.plan.Request.xlsx)
and as decided in WG, please complete following actions:

Add following attributes in TransportationServiceCode **in **Main**TransportationService:** 

- [ ] CodeListAgencyIdentifier, optional
- [ ] CodeListIdentifier, optional
- [ ] CodeListVersionIdentifier, optional 

Add following attributes in TransportationServiceCode **in **Additional**TransportationService:** 

- [ ] CodeListAgencyIdentifier, optional
- [ ] CodeListIdentifier, optional
- [ ] CodeListVersionIdentifier, optional

**Comment by PeterLBorresen** [comment]
Done
