### ISSUE TITLE
Remove InsuranceValueAmount and DeclaredStatisticsValueAmount 

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#75]
As decided in WG: remove InsuranceValueAmount and DeclaredStatisticsValueAmount under Consignment in Transport Execution Plan Request. 

actions: 
- [x] remove InsuranceValueAmount
- [ ] remove DeclaredStatisticsValueAmount

https://test-docs.peppol.eu/logistics/transport-execution/syntax/TransportExecutionPlanRequest/cac-Consignment/cbc-InsuranceValueAmount/ 

https://test-docs.peppol.eu/logistics/transport-execution/syntax/TransportExecutionPlanRequest/cac-Consignment/cbc-DeclaredStatisticsValueAmount/

**Comment by agrindst** [comment]
InsuranceValueAmount is removed from Transport Execution Plan Request. 

There has been a suggestion to move Declared StatisticsValueAmount to consignment-level (an item has to be declared at service level) 

Actions: 

- [ ] make a suggestion

**Comment by agrindst** [comment]
remove InsuranceValueAmount

**Comment by PeterLBorresen** [comment]
Done

**Comment by agrindst** [comment]
completed
