### ISSUE TITLE
Create a rule l RequestedPickupTransportEvent and RequestedDeliveryTransportEvent

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#76]
As commented in WG meeting, 

As commented in: 
[Comments l Transport Execution plan Request.xlsx](https://github.com/OpenPEPPOL/logistics-bis/files/11321786/Comments.l.Transport.Execution.plan.Request.xlsx)

both Location and Period under RequestedPickupTransportEvent under consignment should be optional, however when one is optional the other should be mandatory. 

Actions: 

- [x] change **Location** under RequestedPickupTransportEvent under consignment to optional
- [x] change **Period** under RequestedPickupTransportEvent under consignment to optional 
- [ ] create a rule that when one is optional the other needs to be mandatory 

https://test-docs.peppol.eu/logistics/transport-execution/syntax/TransportExecutionPlanRequest/cac-Consignment/cac-RequestedPickupTransportEvent/

**Comment by agrindst** [comment]
I am sorry, 
You are completely right. 

Please execute, and comment when it is completed.

**Comment by PeterLBorresen** [comment]
Done

**Comment by agrindst** [comment]
both RequestedPickupTransportEvent and RequestedDeliveryTransportEvent are optional. 


Action points:

- [ ] create a rule that either RequestedPickupTransportEvent or RequestedDeliveryTransportEvent needs to be present in a TransportExecutionPlanRequest

**Comment by agrindst** [comment]
closing this issue as it is duplicated in #139
