### ISSUE TITLE
Change MainCarriageShipmentStage to optional 

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#78]
as decided in WG, we will keep MainCarriageShipmentStage, however, we have to change it to optional. 

Actions: 
- [x] change MainCarriageShipmentStage to optional 

@PeterLBorresen, please complete this action 

Background information, some transportation customers want to decide what type of transport they are requesting, (flight, boat etc..). However, some transportation customers are only requesting transport of goods from A to B, and do not care what kind of transportation.

**Comment by PeterLBorresen** [comment]
done

**Comment by agrindst** [comment]
completed
