### ISSUE TITLE
Remove TransportMeans under MainCarriageShipmentStage

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#81]
as decided in WG: 
information about license plates iditifier is not relevant in Transport execution plan request

actions:
- [ ] remove TransportMeans under MainCarriageShipmentStage, under consignment

[Comments l Transport Execution plan Request.xlsx](https://github.com/OpenPEPPOL/logistics-bis/files/11322197/Comments.l.Transport.Execution.plan.Request.xlsx)

https://test-docs.peppol.eu/logistics/transport-execution/syntax/TransportExecutionPlanRequest/cac-Consignment/cac-MainCarriageShipmentStage/cac-TransportMeans/

**Comment by PeterLBorresen** [comment]
done

**Comment by agrindst** [comment]
completed
