### ISSUE TITLE
Item certificate

### ISSUE THREAD

**Issue by PeterLBorresen** [OpenPEPPOL/logistics-bis#83]
Is there a need for Item certificates (e.g. transport of live animals, transport of skin and foods) during transport? Is this a thing the transporter need or can he refer back to the supplier?

**Comment by agrindst** [comment]
requesting for more information: 

- Tomi is going to request more information. 
- will ask bring as well

**Comment by agrindst** [comment]
We have Item Certificate in Advanced Despatch Avice, and is not needed in Waybill
