### ISSUE TITLE
Change Cardinality, and complete following actions in Transport Execution Plan 

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#85]
Please complete following actions: 

**SenderParty**
- [x] Change cardinality to optional for PartyIdentification
- [x] Change cardinality to optional for ShemeID (PartyIdendification/ID) 
- [x] Change cardinality to optional for PostalAdress

**Reciever Party**
- [x] Change cardinality to optional for PartyIdentification
- [x] Change cardinality to optional for ShemeID (PartyIdendification/ID) 
- [x] Change cardinality to optional for PostalAdress

**TransportUserParty**
- [x] please remove EndpointID
- [x] Change cardinality to optional for PartyIdentification
- [x] Change cardinality to optional for ShemeID (PartyIdendification/ID) 
- [x] Change cardinality to optional for PostalAdress

**TransportServiceProviderParty**
- [x] please remove EndpointID
- [x] Change cardinality to optional for PartyIdentification
- [x] Change cardinality to optional for ShemeID (PartyIdendification/ID) 
- [x] Change cardinality to optional for PostalAdress
- [x] Change cardinality to optional for StreetName 

**BillToParty**
- [x] please remove EndpointID
- [x] Change cardinality to optional for PartyIdentification
- [x] Change cardinality to optional for ShemeID (PartyIdendification/ID) 
- [x] Change cardinality to optional for PostalAdress

**Consignment**
- [x] remove NetWeightMeasure
- [x] removeNetNetWeightMeasure
- [x] remove NetVolumeMeasure
- [x] change cardinality to optional for TotalStransportHandlingUnitWuantity

**RequestedPickupTransportEvent** 
- [x] change cardinality to optional for ID under Location
- [x] change cardinality to optional for StartDate under Period 

**PlannedPickupTransportEvent** 
- [x] change cardinality to optional for ID under Location
- [x] change cardinality to optional for StartDate under Period 

**RequestedDeliveryTransportEvent** 
- [x] change cardinality to optional for ID under Location
- [x] change cardinality to optional for StartDate under Period 

**PlannedDeliveryTransportEvent** 
- [x] change cardinality to optional for ID under Location
- [x] change cardinality to optional for StartDate under Period 

**ConsigneeParty** 
- [x] remove EndpointID
- [x] change cardinality to optional for StreetName
- [x] change cardinality to optional for CityName
- [x] change cardinality to optional for PostalZone
- [x] change cardinality to mandatory for IdentificationCode under PostalAdress/Country 
- [x] change cardinality to optional for PartyLegalEntity 
- [x] change cardinality to mandatory for IdentificationCode under PartyLegalEntity/RegistrationAdress/Country 

**ConsignorParty** 
- [x] remove EndpointID
- [x] change cardinality to optional for StreetName
- [x] change cardinality to optional for CityName
- [x] change cardinality to optional for PostalZone
- [x] change cardinality to mandatory for IdentificationCode under PostalAdress/Country 
- [x] change cardinality to optional for PartyLegalEntity 
- [x] change cardinality to mandatory for IdentificationCode under PartyLegalEntity/RegistrationAdress/Country  

**OriginalDepartureCountry**
- [x] change cardinality to mandatory for IdentificationCode

**FinalDestinationCountry**
- [x] change cardinality to mandatory for IdentificationCode

**CarrierParty (in MainCarriageShipmentStage)** 
- [x] change cardinality to mandatory for CarrierParty
- [x] remove EndpointID
- [x] change cardinality to optional for StreetName
- [x] change cardinality to optional for CityName
- [x] change cardinality to optional for PostalZone
- [x] change cardinality to mandatory for IdentificationCode under PostalAdress/Country 
- [x] change cardinality to mandatory for IdentificationCode under PartyLegalEntity/RegistrationAdress/Country 

**MainCarriageShipmentStage** 

- [x] change cardinality to optional for HazardousRiskIndicator
- [x] remove TransportMeans
- [x] remove RequestedDepatureTransportEvent
- [x] remove RequestedArrivalTransportEvent
- [x] remove PlannedDepartureTransportEvent
- [x] remove Planned ArrivalTransportEvent

**Comment by agrindst** [comment]
[Comments TransportExecutionPlan .xlsx](https://github.com/OpenPEPPOL/logistics-bis/files/11391105/Comments.TransportExecutionPlan.xlsx)

**Comment by PeterLBorresen** [comment]
Done

**Comment by agrindst** [comment]
completed
