### ISSUE TITLE
Add schemeDataURI to AdditionalItemProperty

### ISSUE THREAD

**Issue by RikardLarsson-BEAst** [OpenPEPPOL/logistics-bis#90]
/DespatchAdvice/DespatchLine/Item/AdditionalItemProperty

**Comment by agrindst** [comment]
@JorgenErlandsson , please complete this issue

actions:
- [ ] Add schemeDataURI to AdditionalItemProperty

**Comment by JorgenErlandsson** [comment]
This issue is now fixed and can be closed.
