### ISSUE TITLE
Remove AltitudeMeasure from LocationCoordinate

### ISSUE THREAD

**Issue by PeterLBorresen** [OpenPEPPOL/logistics-bis#92]
It does not make sense to have an AltitudeMeassure in LodationCoordinate. What is the usecase for this?

**Comment by JorgenErlandsson** [comment]
For the DespatchAddress it sometimes is important to specify from which deapth the masses come when digging a hole, especially if the masses are polluted. For DeliveryLocation I see no use of it, but it was once in time decided that we wanted to have the same structure.

**Comment by agrindst** [comment]
Decided not to remove AltitudeMeasure form locationCoordinate
