### ISSUE TITLE
Make cac:Shipment/cac:Consignment/cbc:HandlingCode/@listID mandatory

### ISSUE THREAD

**Issue by areberg** [OpenPEPPOL/logistics-bis#97]

**Comment by JorgenErlandsson** [comment]
This issue is now solved and can be closed.

**Comment by JorgenErlandsson** [comment]
This is now fixed for ADA and RA.

**Comment by JorgenErlandsson** [comment]
To be re-assigned to Peter for the remaining three.

**Comment by PeterLBorresen** [comment]
Done for Transport Execution Plan + Transport Execution Plan request

**Comment by PeterLBorresen** [comment]
Done in Waybill as well
