### ISSUE TITLE
Cardinality, CarrierAssignedID 

### ISSUE THREAD

**Issue by agrindst** [OpenPEPPOL/logistics-bis#99]
There is an ongoing discussion wether to keep CarrierAssignedID in the Waybill optional, or change it to mandatory. 

This was first adressed in WG meeting, and found out that there is need for input from the Project Group. 
In addition, Tomi was going to have a meeting with Finnair, where he would ask for their input. 

[Kopi av Waybill comments.xlsx](https://github.com/OpenPEPPOL/logistics-bis/files/11622005/Kopi.av.Waybill.comments.xlsx)

**Comment by agrindst** [comment]
Decided to change CharrierAssignedID to optional, and review this again after the review period


@PeterLBorresen please complete following actions:

- [ ] change CarrierAssignedID to optional

**Comment by PeterLBorresen** [comment]
Done
